/*
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fr.enseeiht.ide.contentassist.antlr.internal.InternalGAMEParser;
import fr.enseeiht.services.GAMEGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class GAMEParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(GAMEGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, GAMEGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getVisibiliteAccess().getAlternatives(), "rule__Visibilite__Alternatives");
			builder.put(grammarAccess.getJeuAccess().getGroup(), "rule__Jeu__Group__0");
			builder.put(grammarAccess.getCheminAccess().getGroup(), "rule__Chemin__Group__0");
			builder.put(grammarAccess.getPersonneAccess().getGroup(), "rule__Personne__Group__0");
			builder.put(grammarAccess.getInteractionAccess().getGroup(), "rule__Interaction__Group__0");
			builder.put(grammarAccess.getChoixAccess().getGroup(), "rule__Choix__Group__0");
			builder.put(grammarAccess.getObjetAccess().getGroup(), "rule__Objet__Group__0");
			builder.put(grammarAccess.getDescriptionAccess().getGroup(), "rule__Description__Group__0");
			builder.put(grammarAccess.getConditionAccess().getGroup(), "rule__Condition__Group__0");
			builder.put(grammarAccess.getConnaissanceAccess().getGroup(), "rule__Connaissance__Group__0");
			builder.put(grammarAccess.getExplorateurAccess().getGroup(), "rule__Explorateur__Group__0");
			builder.put(grammarAccess.getLieuAccess().getGroup(), "rule__Lieu__Group__0");
			builder.put(grammarAccess.getLieuAccess().getGroup_4(), "rule__Lieu__Group_4__0");
			builder.put(grammarAccess.getLieuAccess().getGroup_5(), "rule__Lieu__Group_5__0");
			builder.put(grammarAccess.getLieuAccess().getGroup_6(), "rule__Lieu__Group_6__0");
			builder.put(grammarAccess.getJeuAccess().getNameAssignment_1(), "rule__Jeu__NameAssignment_1");
			builder.put(grammarAccess.getJeuAccess().getExplorateurAssignment_3(), "rule__Jeu__ExplorateurAssignment_3");
			builder.put(grammarAccess.getJeuAccess().getLieuxAssignment_4(), "rule__Jeu__LieuxAssignment_4");
			builder.put(grammarAccess.getJeuAccess().getObjetsAssignment_5(), "rule__Jeu__ObjetsAssignment_5");
			builder.put(grammarAccess.getJeuAccess().getConnaissancesAssignment_6(), "rule__Jeu__ConnaissancesAssignment_6");
			builder.put(grammarAccess.getJeuAccess().getPersonnesAssignment_7(), "rule__Jeu__PersonnesAssignment_7");
			builder.put(grammarAccess.getJeuAccess().getCheminsAssignment_8(), "rule__Jeu__CheminsAssignment_8");
			builder.put(grammarAccess.getCheminAccess().getNameAssignment_1(), "rule__Chemin__NameAssignment_1");
			builder.put(grammarAccess.getCheminAccess().getDescriptionsAssignment_3(), "rule__Chemin__DescriptionsAssignment_3");
			builder.put(grammarAccess.getCheminAccess().getDepartAssignment_5(), "rule__Chemin__DepartAssignment_5");
			builder.put(grammarAccess.getCheminAccess().getArriveAssignment_7(), "rule__Chemin__ArriveAssignment_7");
			builder.put(grammarAccess.getCheminAccess().getVisibiliteAssignment_8(), "rule__Chemin__VisibiliteAssignment_8");
			builder.put(grammarAccess.getCheminAccess().getConditionsVisibiliteAssignment_10(), "rule__Chemin__ConditionsVisibiliteAssignment_10");
			builder.put(grammarAccess.getPersonneAccess().getNameAssignment_1(), "rule__Personne__NameAssignment_1");
			builder.put(grammarAccess.getPersonneAccess().getDescriptionsAssignment_3(), "rule__Personne__DescriptionsAssignment_3");
			builder.put(grammarAccess.getPersonneAccess().getInteractionAssignment_4(), "rule__Personne__InteractionAssignment_4");
			builder.put(grammarAccess.getPersonneAccess().getVisibiliteAssignment_5(), "rule__Personne__VisibiliteAssignment_5");
			builder.put(grammarAccess.getPersonneAccess().getConditionsVisibiliteAssignment_7(), "rule__Personne__ConditionsVisibiliteAssignment_7");
			builder.put(grammarAccess.getInteractionAccess().getChoixAssignment_2(), "rule__Interaction__ChoixAssignment_2");
			builder.put(grammarAccess.getChoixAccess().getNameAssignment_1(), "rule__Choix__NameAssignment_1");
			builder.put(grammarAccess.getObjetAccess().getNameAssignment_1(), "rule__Objet__NameAssignment_1");
			builder.put(grammarAccess.getObjetAccess().getDescriptionsAssignment_3(), "rule__Objet__DescriptionsAssignment_3");
			builder.put(grammarAccess.getObjetAccess().getTailleAssignment_5(), "rule__Objet__TailleAssignment_5");
			builder.put(grammarAccess.getDescriptionAccess().getTextAssignment_2(), "rule__Description__TextAssignment_2");
			builder.put(grammarAccess.getConditionAccess().getNameAssignment_1(), "rule__Condition__NameAssignment_1");
			builder.put(grammarAccess.getConnaissanceAccess().getNameAssignment_1(), "rule__Connaissance__NameAssignment_1");
			builder.put(grammarAccess.getExplorateurAccess().getNameAssignment_1(), "rule__Explorateur__NameAssignment_1");
			builder.put(grammarAccess.getExplorateurAccess().getTailleAssignment_4(), "rule__Explorateur__TailleAssignment_4");
			builder.put(grammarAccess.getExplorateurAccess().getObjetsAssignment_6(), "rule__Explorateur__ObjetsAssignment_6");
			builder.put(grammarAccess.getExplorateurAccess().getConnaissancesAssignment_8(), "rule__Explorateur__ConnaissancesAssignment_8");
			builder.put(grammarAccess.getExplorateurAccess().getLocalisationAssignment_10(), "rule__Explorateur__LocalisationAssignment_10");
			builder.put(grammarAccess.getLieuAccess().getNameAssignment_1(), "rule__Lieu__NameAssignment_1");
			builder.put(grammarAccess.getLieuAccess().getDescriptionsAssignment_3(), "rule__Lieu__DescriptionsAssignment_3");
			builder.put(grammarAccess.getLieuAccess().getObjetsAssignment_4_1(), "rule__Lieu__ObjetsAssignment_4_1");
			builder.put(grammarAccess.getLieuAccess().getConnaissancesAssignment_5_1(), "rule__Lieu__ConnaissancesAssignment_5_1");
			builder.put(grammarAccess.getLieuAccess().getPersonnesAssignment_6_1(), "rule__Lieu__PersonnesAssignment_6_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private GAMEGrammarAccess grammarAccess;

	@Override
	protected InternalGAMEParser createParser() {
		InternalGAMEParser result = new InternalGAMEParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GAMEGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GAMEGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
