/*
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fr.enseeiht.ide.contentassist.antlr.internal.InternalGAMEParser;
import fr.enseeiht.services.GAMEGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class GAMEParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(GAMEGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, GAMEGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getVisibiliteAccess().getAlternatives(), "rule__Visibilite__Alternatives");
			builder.put(grammarAccess.getOuvertureAccess().getAlternatives(), "rule__Ouverture__Alternatives");
			builder.put(grammarAccess.getJeuAccess().getGroup(), "rule__Jeu__Group__0");
			builder.put(grammarAccess.getCheminAccess().getGroup(), "rule__Chemin__Group__0");
			builder.put(grammarAccess.getCheminAccess().getGroup_9(), "rule__Chemin__Group_9__0");
			builder.put(grammarAccess.getCheminAccess().getGroup_11(), "rule__Chemin__Group_11__0");
			builder.put(grammarAccess.getPersonneAccess().getGroup(), "rule__Personne__Group__0");
			builder.put(grammarAccess.getPersonneAccess().getGroup_6(), "rule__Personne__Group_6__0");
			builder.put(grammarAccess.getInteractionAccess().getGroup(), "rule__Interaction__Group__0");
			builder.put(grammarAccess.getChoixAccess().getGroup(), "rule__Choix__Group__0");
			builder.put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
			builder.put(grammarAccess.getEchangeAccess().getGroup(), "rule__Echange__Group__0");
			builder.put(grammarAccess.getEchangeAccess().getGroup_3(), "rule__Echange__Group_3__0");
			builder.put(grammarAccess.getEchangeAccess().getGroup_4(), "rule__Echange__Group_4__0");
			builder.put(grammarAccess.getEchangeAccess().getGroup_5(), "rule__Echange__Group_5__0");
			builder.put(grammarAccess.getObjetAccess().getGroup(), "rule__Objet__Group__0");
			builder.put(grammarAccess.getObjetAccess().getGroup_7(), "rule__Objet__Group_7__0");
			builder.put(grammarAccess.getDescriptionAccess().getGroup(), "rule__Description__Group__0");
			builder.put(grammarAccess.getConditionAccess().getGroup(), "rule__Condition__Group__0");
			builder.put(grammarAccess.getConditionAccess().getGroup_3(), "rule__Condition__Group_3__0");
			builder.put(grammarAccess.getConditionAccess().getGroup_4(), "rule__Condition__Group_4__0");
			builder.put(grammarAccess.getConditionAccess().getGroup_5(), "rule__Condition__Group_5__0");
			builder.put(grammarAccess.getConnaissanceAccess().getGroup(), "rule__Connaissance__Group__0");
			builder.put(grammarAccess.getConnaissanceAccess().getGroup_4(), "rule__Connaissance__Group_4__0");
			builder.put(grammarAccess.getExplorateurAccess().getGroup(), "rule__Explorateur__Group__0");
			builder.put(grammarAccess.getLieuAccess().getGroup(), "rule__Lieu__Group__0");
			builder.put(grammarAccess.getLieuAccess().getGroup_4(), "rule__Lieu__Group_4__0");
			builder.put(grammarAccess.getLieuAccess().getGroup_5(), "rule__Lieu__Group_5__0");
			builder.put(grammarAccess.getLieuAccess().getGroup_6(), "rule__Lieu__Group_6__0");
			builder.put(grammarAccess.getLieuAccess().getGroup_7(), "rule__Lieu__Group_7__0");
			builder.put(grammarAccess.getJeuAccess().getNameAssignment_1(), "rule__Jeu__NameAssignment_1");
			builder.put(grammarAccess.getJeuAccess().getExplorateurAssignment_3(), "rule__Jeu__ExplorateurAssignment_3");
			builder.put(grammarAccess.getJeuAccess().getPointDepartAssignment_5(), "rule__Jeu__PointDepartAssignment_5");
			builder.put(grammarAccess.getJeuAccess().getPointFinAssignment_7(), "rule__Jeu__PointFinAssignment_7");
			builder.put(grammarAccess.getJeuAccess().getLieuxAssignment_8(), "rule__Jeu__LieuxAssignment_8");
			builder.put(grammarAccess.getJeuAccess().getObjetsAssignment_9(), "rule__Jeu__ObjetsAssignment_9");
			builder.put(grammarAccess.getJeuAccess().getConnaissancesAssignment_10(), "rule__Jeu__ConnaissancesAssignment_10");
			builder.put(grammarAccess.getJeuAccess().getPersonnesAssignment_11(), "rule__Jeu__PersonnesAssignment_11");
			builder.put(grammarAccess.getJeuAccess().getCheminsAssignment_12(), "rule__Jeu__CheminsAssignment_12");
			builder.put(grammarAccess.getCheminAccess().getNameAssignment_1(), "rule__Chemin__NameAssignment_1");
			builder.put(grammarAccess.getCheminAccess().getDescriptionsAssignment_3(), "rule__Chemin__DescriptionsAssignment_3");
			builder.put(grammarAccess.getCheminAccess().getDepartAssignment_5(), "rule__Chemin__DepartAssignment_5");
			builder.put(grammarAccess.getCheminAccess().getArriveAssignment_7(), "rule__Chemin__ArriveAssignment_7");
			builder.put(grammarAccess.getCheminAccess().getVisibiliteAssignment_8(), "rule__Chemin__VisibiliteAssignment_8");
			builder.put(grammarAccess.getCheminAccess().getConditionsVisibiliteAssignment_9_1(), "rule__Chemin__ConditionsVisibiliteAssignment_9_1");
			builder.put(grammarAccess.getCheminAccess().getOuvertureAssignment_10(), "rule__Chemin__OuvertureAssignment_10");
			builder.put(grammarAccess.getCheminAccess().getConditionsOuvertureAssignment_11_1(), "rule__Chemin__ConditionsOuvertureAssignment_11_1");
			builder.put(grammarAccess.getPersonneAccess().getNameAssignment_1(), "rule__Personne__NameAssignment_1");
			builder.put(grammarAccess.getPersonneAccess().getDescriptionsAssignment_3(), "rule__Personne__DescriptionsAssignment_3");
			builder.put(grammarAccess.getPersonneAccess().getInteractionAssignment_4(), "rule__Personne__InteractionAssignment_4");
			builder.put(grammarAccess.getPersonneAccess().getVisibiliteAssignment_5(), "rule__Personne__VisibiliteAssignment_5");
			builder.put(grammarAccess.getPersonneAccess().getConditionsVisibiliteAssignment_6_1(), "rule__Personne__ConditionsVisibiliteAssignment_6_1");
			builder.put(grammarAccess.getInteractionAccess().getEchangesAssignment_2(), "rule__Interaction__EchangesAssignment_2");
			builder.put(grammarAccess.getInteractionAccess().getChoixAssignment_3(), "rule__Interaction__ChoixAssignment_3");
			builder.put(grammarAccess.getChoixAccess().getNameAssignment_1(), "rule__Choix__NameAssignment_1");
			builder.put(grammarAccess.getChoixAccess().getActionsAssignment_3(), "rule__Choix__ActionsAssignment_3");
			builder.put(grammarAccess.getChoixAccess().getConditionsAssignment_4(), "rule__Choix__ConditionsAssignment_4");
			builder.put(grammarAccess.getActionAccess().getNameAssignment_1(), "rule__Action__NameAssignment_1");
			builder.put(grammarAccess.getActionAccess().getDescriptionsAssignment_3(), "rule__Action__DescriptionsAssignment_3");
			builder.put(grammarAccess.getActionAccess().getConditionsAssignment_4(), "rule__Action__ConditionsAssignment_4");
			builder.put(grammarAccess.getActionAccess().getEchangesAssignment_5(), "rule__Action__EchangesAssignment_5");
			builder.put(grammarAccess.getEchangeAccess().getObjetsDonneAssignment_3_1(), "rule__Echange__ObjetsDonneAssignment_3_1");
			builder.put(grammarAccess.getEchangeAccess().getObjetsPrisAssignment_4_1(), "rule__Echange__ObjetsPrisAssignment_4_1");
			builder.put(grammarAccess.getEchangeAccess().getConnaissancesAssignment_5_1(), "rule__Echange__ConnaissancesAssignment_5_1");
			builder.put(grammarAccess.getEchangeAccess().getConditionsAssignment_6(), "rule__Echange__ConditionsAssignment_6");
			builder.put(grammarAccess.getObjetAccess().getNameAssignment_1(), "rule__Objet__NameAssignment_1");
			builder.put(grammarAccess.getObjetAccess().getDescriptionsAssignment_3(), "rule__Objet__DescriptionsAssignment_3");
			builder.put(grammarAccess.getObjetAccess().getTailleAssignment_5(), "rule__Objet__TailleAssignment_5");
			builder.put(grammarAccess.getObjetAccess().getVisibiliteAssignment_6(), "rule__Objet__VisibiliteAssignment_6");
			builder.put(grammarAccess.getObjetAccess().getConditionsVisibiliteAssignment_7_1(), "rule__Objet__ConditionsVisibiliteAssignment_7_1");
			builder.put(grammarAccess.getDescriptionAccess().getTextAssignment_2(), "rule__Description__TextAssignment_2");
			builder.put(grammarAccess.getConditionAccess().getNameAssignment_1(), "rule__Condition__NameAssignment_1");
			builder.put(grammarAccess.getConditionAccess().getObjetsAssignment_3_2(), "rule__Condition__ObjetsAssignment_3_2");
			builder.put(grammarAccess.getConditionAccess().getObjetsAssignment_4_2(), "rule__Condition__ObjetsAssignment_4_2");
			builder.put(grammarAccess.getConditionAccess().getConnaissancesAssignment_5_2(), "rule__Condition__ConnaissancesAssignment_5_2");
			builder.put(grammarAccess.getConnaissanceAccess().getNameAssignment_1(), "rule__Connaissance__NameAssignment_1");
			builder.put(grammarAccess.getConnaissanceAccess().getVisibiliteAssignment_3(), "rule__Connaissance__VisibiliteAssignment_3");
			builder.put(grammarAccess.getConnaissanceAccess().getConditionsVisibiliteAssignment_4_1(), "rule__Connaissance__ConditionsVisibiliteAssignment_4_1");
			builder.put(grammarAccess.getExplorateurAccess().getNameAssignment_1(), "rule__Explorateur__NameAssignment_1");
			builder.put(grammarAccess.getExplorateurAccess().getTailleAssignment_4(), "rule__Explorateur__TailleAssignment_4");
			builder.put(grammarAccess.getExplorateurAccess().getObjetsAssignment_6(), "rule__Explorateur__ObjetsAssignment_6");
			builder.put(grammarAccess.getExplorateurAccess().getConnaissancesAssignment_8(), "rule__Explorateur__ConnaissancesAssignment_8");
			builder.put(grammarAccess.getExplorateurAccess().getLocalisationAssignment_10(), "rule__Explorateur__LocalisationAssignment_10");
			builder.put(grammarAccess.getLieuAccess().getNameAssignment_1(), "rule__Lieu__NameAssignment_1");
			builder.put(grammarAccess.getLieuAccess().getDescriptionsAssignment_3(), "rule__Lieu__DescriptionsAssignment_3");
			builder.put(grammarAccess.getLieuAccess().getObjetsAssignment_4_2(), "rule__Lieu__ObjetsAssignment_4_2");
			builder.put(grammarAccess.getLieuAccess().getConnaissancesAssignment_5_2(), "rule__Lieu__ConnaissancesAssignment_5_2");
			builder.put(grammarAccess.getLieuAccess().getPersonnesAssignment_6_2(), "rule__Lieu__PersonnesAssignment_6_2");
			builder.put(grammarAccess.getLieuAccess().getCheminspossibleAssignment_7_1(), "rule__Lieu__CheminspossibleAssignment_7_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private GAMEGrammarAccess grammarAccess;

	@Override
	protected InternalGAMEParser createParser() {
		InternalGAMEParser result = new InternalGAMEParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GAMEGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GAMEGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
