/*
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class GAMEGrammarAccess extends AbstractGrammarElementFinder {
	
	public class JeuElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.enseeiht.GAME.Jeu");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cJeuKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cExplorateurAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cExplorateurExplorateurParserRuleCall_3_0 = (RuleCall)cExplorateurAssignment_3.eContents().get(0);
		private final Keyword cPointDepartKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cPointDepartAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cPointDepartLieuCrossReference_5_0 = (CrossReference)cPointDepartAssignment_5.eContents().get(0);
		private final RuleCall cPointDepartLieuIDTerminalRuleCall_5_0_1 = (RuleCall)cPointDepartLieuCrossReference_5_0.eContents().get(1);
		private final Keyword cPointFinKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cPointFinAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cPointFinLieuCrossReference_7_0 = (CrossReference)cPointFinAssignment_7.eContents().get(0);
		private final RuleCall cPointFinLieuIDTerminalRuleCall_7_0_1 = (RuleCall)cPointFinLieuCrossReference_7_0.eContents().get(1);
		private final Assignment cLieuxAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cLieuxLieuParserRuleCall_8_0 = (RuleCall)cLieuxAssignment_8.eContents().get(0);
		private final Assignment cObjetsAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cObjetsObjetParserRuleCall_9_0 = (RuleCall)cObjetsAssignment_9.eContents().get(0);
		private final Assignment cObjetAvecQuantiteAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cObjetAvecQuantiteObjetAvecQuantiteParserRuleCall_10_0 = (RuleCall)cObjetAvecQuantiteAssignment_10.eContents().get(0);
		private final Assignment cConnaissancesAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cConnaissancesConnaissanceParserRuleCall_11_0 = (RuleCall)cConnaissancesAssignment_11.eContents().get(0);
		private final Assignment cPersonnesAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cPersonnesPersonneParserRuleCall_12_0 = (RuleCall)cPersonnesAssignment_12.eContents().get(0);
		private final Assignment cCheminsAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cCheminsCheminParserRuleCall_13_0 = (RuleCall)cCheminsAssignment_13.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//Jeu:
		//	'jeu' name=ID '{'
		//	explorateur=Explorateur
		//	'pointDepart' pointDepart=[Lieu]
		//	'pointFin' pointFin+=[Lieu]+
		//	lieux+=Lieu*
		//	Objets+=Objet*
		//	ObjetAvecQuantite+=ObjetAvecQuantite*
		//	Connaissances+=Connaissance*
		//	personnes+=Personne*
		//	chemins+=Chemin*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'jeu' name=ID '{' explorateur=Explorateur 'pointDepart' pointDepart=[Lieu] 'pointFin' pointFin+=[Lieu]+ lieux+=Lieu*
		//Objets+=Objet* ObjetAvecQuantite+=ObjetAvecQuantite* Connaissances+=Connaissance* personnes+=Personne*
		//chemins+=Chemin* '}'
		public Group getGroup() { return cGroup; }
		
		//'jeu'
		public Keyword getJeuKeyword_0() { return cJeuKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//explorateur=Explorateur
		public Assignment getExplorateurAssignment_3() { return cExplorateurAssignment_3; }
		
		//Explorateur
		public RuleCall getExplorateurExplorateurParserRuleCall_3_0() { return cExplorateurExplorateurParserRuleCall_3_0; }
		
		//'pointDepart'
		public Keyword getPointDepartKeyword_4() { return cPointDepartKeyword_4; }
		
		//pointDepart=[Lieu]
		public Assignment getPointDepartAssignment_5() { return cPointDepartAssignment_5; }
		
		//[Lieu]
		public CrossReference getPointDepartLieuCrossReference_5_0() { return cPointDepartLieuCrossReference_5_0; }
		
		//ID
		public RuleCall getPointDepartLieuIDTerminalRuleCall_5_0_1() { return cPointDepartLieuIDTerminalRuleCall_5_0_1; }
		
		//'pointFin'
		public Keyword getPointFinKeyword_6() { return cPointFinKeyword_6; }
		
		//pointFin+=[Lieu]+
		public Assignment getPointFinAssignment_7() { return cPointFinAssignment_7; }
		
		//[Lieu]
		public CrossReference getPointFinLieuCrossReference_7_0() { return cPointFinLieuCrossReference_7_0; }
		
		//ID
		public RuleCall getPointFinLieuIDTerminalRuleCall_7_0_1() { return cPointFinLieuIDTerminalRuleCall_7_0_1; }
		
		//lieux+=Lieu*
		public Assignment getLieuxAssignment_8() { return cLieuxAssignment_8; }
		
		//Lieu
		public RuleCall getLieuxLieuParserRuleCall_8_0() { return cLieuxLieuParserRuleCall_8_0; }
		
		//Objets+=Objet*
		public Assignment getObjetsAssignment_9() { return cObjetsAssignment_9; }
		
		//Objet
		public RuleCall getObjetsObjetParserRuleCall_9_0() { return cObjetsObjetParserRuleCall_9_0; }
		
		//ObjetAvecQuantite+=ObjetAvecQuantite*
		public Assignment getObjetAvecQuantiteAssignment_10() { return cObjetAvecQuantiteAssignment_10; }
		
		//ObjetAvecQuantite
		public RuleCall getObjetAvecQuantiteObjetAvecQuantiteParserRuleCall_10_0() { return cObjetAvecQuantiteObjetAvecQuantiteParserRuleCall_10_0; }
		
		//Connaissances+=Connaissance*
		public Assignment getConnaissancesAssignment_11() { return cConnaissancesAssignment_11; }
		
		//Connaissance
		public RuleCall getConnaissancesConnaissanceParserRuleCall_11_0() { return cConnaissancesConnaissanceParserRuleCall_11_0; }
		
		//personnes+=Personne*
		public Assignment getPersonnesAssignment_12() { return cPersonnesAssignment_12; }
		
		//Personne
		public RuleCall getPersonnesPersonneParserRuleCall_12_0() { return cPersonnesPersonneParserRuleCall_12_0; }
		
		//chemins+=Chemin*
		public Assignment getCheminsAssignment_13() { return cCheminsAssignment_13; }
		
		//Chemin
		public RuleCall getCheminsCheminParserRuleCall_13_0() { return cCheminsCheminParserRuleCall_13_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}
	public class CheminElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.enseeiht.GAME.Chemin");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCheminKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDescriptionsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDescriptionsDescriptionParserRuleCall_3_0 = (RuleCall)cDescriptionsAssignment_3.eContents().get(0);
		private final Keyword cDeKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cDepartAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cDepartLieuCrossReference_5_0 = (CrossReference)cDepartAssignment_5.eContents().get(0);
		private final RuleCall cDepartLieuIDTerminalRuleCall_5_0_1 = (RuleCall)cDepartLieuCrossReference_5_0.eContents().get(1);
		private final Keyword cVersKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cArriveAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cArriveLieuCrossReference_7_0 = (CrossReference)cArriveAssignment_7.eContents().get(0);
		private final RuleCall cArriveLieuIDTerminalRuleCall_7_0_1 = (RuleCall)cArriveLieuCrossReference_7_0.eContents().get(1);
		private final Assignment cVisibiliteAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cVisibiliteVisibiliteEnumRuleCall_8_0 = (RuleCall)cVisibiliteAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cSiKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cConditionsVisibiliteAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cConditionsVisibiliteConditionParserRuleCall_9_1_0 = (RuleCall)cConditionsVisibiliteAssignment_9_1.eContents().get(0);
		private final Assignment cOuvertureAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cOuvertureOuvertureEnumRuleCall_10_0 = (RuleCall)cOuvertureAssignment_10.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cSiKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cConditionsOuvertureAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cConditionsOuvertureConditionParserRuleCall_11_1_0 = (RuleCall)cConditionsOuvertureAssignment_11_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Chemin:
		//	'chemin' name=ID '{'
		//	descriptions=Description?
		//	'de' depart=[Lieu]
		//	'vers' arrive=[Lieu] visibilite=Visibilite ('si' conditionsVisibilite=Condition)?
		//	ouverture=Ouverture ('si' conditionsOuverture=Condition)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'chemin' name=ID '{' descriptions=Description? 'de' depart=[Lieu] 'vers' arrive=[Lieu] visibilite=Visibilite ('si'
		//conditionsVisibilite=Condition)? ouverture=Ouverture ('si' conditionsOuverture=Condition)? '}'
		public Group getGroup() { return cGroup; }
		
		//'chemin'
		public Keyword getCheminKeyword_0() { return cCheminKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//descriptions=Description?
		public Assignment getDescriptionsAssignment_3() { return cDescriptionsAssignment_3; }
		
		//Description
		public RuleCall getDescriptionsDescriptionParserRuleCall_3_0() { return cDescriptionsDescriptionParserRuleCall_3_0; }
		
		//'de'
		public Keyword getDeKeyword_4() { return cDeKeyword_4; }
		
		//depart=[Lieu]
		public Assignment getDepartAssignment_5() { return cDepartAssignment_5; }
		
		//[Lieu]
		public CrossReference getDepartLieuCrossReference_5_0() { return cDepartLieuCrossReference_5_0; }
		
		//ID
		public RuleCall getDepartLieuIDTerminalRuleCall_5_0_1() { return cDepartLieuIDTerminalRuleCall_5_0_1; }
		
		//'vers'
		public Keyword getVersKeyword_6() { return cVersKeyword_6; }
		
		//arrive=[Lieu]
		public Assignment getArriveAssignment_7() { return cArriveAssignment_7; }
		
		//[Lieu]
		public CrossReference getArriveLieuCrossReference_7_0() { return cArriveLieuCrossReference_7_0; }
		
		//ID
		public RuleCall getArriveLieuIDTerminalRuleCall_7_0_1() { return cArriveLieuIDTerminalRuleCall_7_0_1; }
		
		//visibilite=Visibilite
		public Assignment getVisibiliteAssignment_8() { return cVisibiliteAssignment_8; }
		
		//Visibilite
		public RuleCall getVisibiliteVisibiliteEnumRuleCall_8_0() { return cVisibiliteVisibiliteEnumRuleCall_8_0; }
		
		//('si' conditionsVisibilite=Condition)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'si'
		public Keyword getSiKeyword_9_0() { return cSiKeyword_9_0; }
		
		//conditionsVisibilite=Condition
		public Assignment getConditionsVisibiliteAssignment_9_1() { return cConditionsVisibiliteAssignment_9_1; }
		
		//Condition
		public RuleCall getConditionsVisibiliteConditionParserRuleCall_9_1_0() { return cConditionsVisibiliteConditionParserRuleCall_9_1_0; }
		
		//ouverture=Ouverture
		public Assignment getOuvertureAssignment_10() { return cOuvertureAssignment_10; }
		
		//Ouverture
		public RuleCall getOuvertureOuvertureEnumRuleCall_10_0() { return cOuvertureOuvertureEnumRuleCall_10_0; }
		
		//('si' conditionsOuverture=Condition)?
		public Group getGroup_11() { return cGroup_11; }
		
		//'si'
		public Keyword getSiKeyword_11_0() { return cSiKeyword_11_0; }
		
		//conditionsOuverture=Condition
		public Assignment getConditionsOuvertureAssignment_11_1() { return cConditionsOuvertureAssignment_11_1; }
		
		//Condition
		public RuleCall getConditionsOuvertureConditionParserRuleCall_11_1_0() { return cConditionsOuvertureConditionParserRuleCall_11_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class PersonneElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.enseeiht.GAME.Personne");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPersonneKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDescriptionsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDescriptionsDescriptionParserRuleCall_3_0 = (RuleCall)cDescriptionsAssignment_3.eContents().get(0);
		private final Assignment cInteractionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cInteractionInteractionParserRuleCall_4_0 = (RuleCall)cInteractionAssignment_4.eContents().get(0);
		private final Assignment cVisibiliteAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cVisibiliteVisibiliteEnumRuleCall_5_0 = (RuleCall)cVisibiliteAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cSiKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cConditionsVisibiliteAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cConditionsVisibiliteConditionParserRuleCall_6_1_0 = (RuleCall)cConditionsVisibiliteAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Personne:
		//	'personne' name=ID '{'
		//	descriptions=Description
		//	interaction=Interaction
		//	visibilite=Visibilite ('si' conditionsVisibilite=Condition)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'personne' name=ID '{' descriptions=Description interaction=Interaction visibilite=Visibilite ('si'
		//conditionsVisibilite=Condition)? '}'
		public Group getGroup() { return cGroup; }
		
		//'personne'
		public Keyword getPersonneKeyword_0() { return cPersonneKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//descriptions=Description
		public Assignment getDescriptionsAssignment_3() { return cDescriptionsAssignment_3; }
		
		//Description
		public RuleCall getDescriptionsDescriptionParserRuleCall_3_0() { return cDescriptionsDescriptionParserRuleCall_3_0; }
		
		//interaction=Interaction
		public Assignment getInteractionAssignment_4() { return cInteractionAssignment_4; }
		
		//Interaction
		public RuleCall getInteractionInteractionParserRuleCall_4_0() { return cInteractionInteractionParserRuleCall_4_0; }
		
		//visibilite=Visibilite
		public Assignment getVisibiliteAssignment_5() { return cVisibiliteAssignment_5; }
		
		//Visibilite
		public RuleCall getVisibiliteVisibiliteEnumRuleCall_5_0() { return cVisibiliteVisibiliteEnumRuleCall_5_0; }
		
		//('si' conditionsVisibilite=Condition)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'si'
		public Keyword getSiKeyword_6_0() { return cSiKeyword_6_0; }
		
		//conditionsVisibilite=Condition
		public Assignment getConditionsVisibiliteAssignment_6_1() { return cConditionsVisibiliteAssignment_6_1; }
		
		//Condition
		public RuleCall getConditionsVisibiliteConditionParserRuleCall_6_1_0() { return cConditionsVisibiliteConditionParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class InteractionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.enseeiht.GAME.Interaction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInteractionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cEchangesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cEchangesEchangeParserRuleCall_2_0 = (RuleCall)cEchangesAssignment_2.eContents().get(0);
		private final Assignment cChoixAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cChoixChoixParserRuleCall_3_0 = (RuleCall)cChoixAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Interaction:
		//	'interaction' '{'
		//	echanges+=Echange*
		//	choix+=Choix+
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'interaction' '{' echanges+=Echange* choix+=Choix+ '}'
		public Group getGroup() { return cGroup; }
		
		//'interaction'
		public Keyword getInteractionKeyword_0() { return cInteractionKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//echanges+=Echange*
		public Assignment getEchangesAssignment_2() { return cEchangesAssignment_2; }
		
		//Echange
		public RuleCall getEchangesEchangeParserRuleCall_2_0() { return cEchangesEchangeParserRuleCall_2_0; }
		
		//choix+=Choix+
		public Assignment getChoixAssignment_3() { return cChoixAssignment_3; }
		
		//Choix
		public RuleCall getChoixChoixParserRuleCall_3_0() { return cChoixChoixParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ChoixElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.enseeiht.GAME.Choix");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cChoixKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cActionsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cActionsActionParserRuleCall_3_0 = (RuleCall)cActionsAssignment_3.eContents().get(0);
		private final Assignment cConditionsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cConditionsConditionParserRuleCall_4_0 = (RuleCall)cConditionsAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Choix:
		//	'choix' name=ID '{'
		//	actions+=Action*
		//	conditions+=Condition*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'choix' name=ID '{' actions+=Action* conditions+=Condition* '}'
		public Group getGroup() { return cGroup; }
		
		//'choix'
		public Keyword getChoixKeyword_0() { return cChoixKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//actions+=Action*
		public Assignment getActionsAssignment_3() { return cActionsAssignment_3; }
		
		//Action
		public RuleCall getActionsActionParserRuleCall_3_0() { return cActionsActionParserRuleCall_3_0; }
		
		//conditions+=Condition*
		public Assignment getConditionsAssignment_4() { return cConditionsAssignment_4; }
		
		//Condition
		public RuleCall getConditionsConditionParserRuleCall_4_0() { return cConditionsConditionParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.enseeiht.GAME.Action");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cActionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDescriptionsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDescriptionsDescriptionParserRuleCall_3_0 = (RuleCall)cDescriptionsAssignment_3.eContents().get(0);
		private final Assignment cConditionsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cConditionsConditionParserRuleCall_4_0 = (RuleCall)cConditionsAssignment_4.eContents().get(0);
		private final Assignment cEchangesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cEchangesEchangeParserRuleCall_5_0 = (RuleCall)cEchangesAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Action:
		//	'action' name=ID '{'
		//	descriptions+=Description conditions+=Condition*
		//	echanges+=Echange+
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'action' name=ID '{' descriptions+=Description conditions+=Condition* echanges+=Echange+ '}'
		public Group getGroup() { return cGroup; }
		
		//'action'
		public Keyword getActionKeyword_0() { return cActionKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//descriptions+=Description
		public Assignment getDescriptionsAssignment_3() { return cDescriptionsAssignment_3; }
		
		//Description
		public RuleCall getDescriptionsDescriptionParserRuleCall_3_0() { return cDescriptionsDescriptionParserRuleCall_3_0; }
		
		//conditions+=Condition*
		public Assignment getConditionsAssignment_4() { return cConditionsAssignment_4; }
		
		//Condition
		public RuleCall getConditionsConditionParserRuleCall_4_0() { return cConditionsConditionParserRuleCall_4_0; }
		
		//echanges+=Echange+
		public Assignment getEchangesAssignment_5() { return cEchangesAssignment_5; }
		
		//Echange
		public RuleCall getEchangesEchangeParserRuleCall_5_0() { return cEchangesEchangeParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class EchangeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.enseeiht.GAME.Echange");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEchangeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEchangeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cObjetsDonneKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cObjetsDonneAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cObjetsDonneObjetCrossReference_3_1_0 = (CrossReference)cObjetsDonneAssignment_3_1.eContents().get(0);
		private final RuleCall cObjetsDonneObjetIDTerminalRuleCall_3_1_0_1 = (RuleCall)cObjetsDonneObjetCrossReference_3_1_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cObjetsPrisKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cObjetsPrisAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cObjetsPrisObjetCrossReference_4_1_0 = (CrossReference)cObjetsPrisAssignment_4_1.eContents().get(0);
		private final RuleCall cObjetsPrisObjetIDTerminalRuleCall_4_1_0_1 = (RuleCall)cObjetsPrisObjetCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cConnaissancesDonneKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cConnaissancesAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cConnaissancesConnaissanceCrossReference_5_1_0 = (CrossReference)cConnaissancesAssignment_5_1.eContents().get(0);
		private final RuleCall cConnaissancesConnaissanceIDTerminalRuleCall_5_1_0_1 = (RuleCall)cConnaissancesConnaissanceCrossReference_5_1_0.eContents().get(1);
		private final Assignment cConditionsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cConditionsConditionParserRuleCall_6_0 = (RuleCall)cConditionsAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Echange:
		//	{Echange} 'echange' '{' ('objetsDonne' objetsDonne+=[Objet]+)? ('objetsPris' objetsPris+=[Objet]+)?
		//	('connaissancesDonne' connaissances+=[Connaissance]+)?
		//	conditions+=Condition*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Echange} 'echange' '{' ('objetsDonne' objetsDonne+=[Objet]+)? ('objetsPris' objetsPris+=[Objet]+)?
		//('connaissancesDonne' connaissances+=[Connaissance]+)? conditions+=Condition* '}'
		public Group getGroup() { return cGroup; }
		
		//{Echange}
		public Action getEchangeAction_0() { return cEchangeAction_0; }
		
		//'echange'
		public Keyword getEchangeKeyword_1() { return cEchangeKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('objetsDonne' objetsDonne+=[Objet]+)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'objetsDonne'
		public Keyword getObjetsDonneKeyword_3_0() { return cObjetsDonneKeyword_3_0; }
		
		//objetsDonne+=[Objet]+
		public Assignment getObjetsDonneAssignment_3_1() { return cObjetsDonneAssignment_3_1; }
		
		//[Objet]
		public CrossReference getObjetsDonneObjetCrossReference_3_1_0() { return cObjetsDonneObjetCrossReference_3_1_0; }
		
		//ID
		public RuleCall getObjetsDonneObjetIDTerminalRuleCall_3_1_0_1() { return cObjetsDonneObjetIDTerminalRuleCall_3_1_0_1; }
		
		//('objetsPris' objetsPris+=[Objet]+)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'objetsPris'
		public Keyword getObjetsPrisKeyword_4_0() { return cObjetsPrisKeyword_4_0; }
		
		//objetsPris+=[Objet]+
		public Assignment getObjetsPrisAssignment_4_1() { return cObjetsPrisAssignment_4_1; }
		
		//[Objet]
		public CrossReference getObjetsPrisObjetCrossReference_4_1_0() { return cObjetsPrisObjetCrossReference_4_1_0; }
		
		//ID
		public RuleCall getObjetsPrisObjetIDTerminalRuleCall_4_1_0_1() { return cObjetsPrisObjetIDTerminalRuleCall_4_1_0_1; }
		
		//('connaissancesDonne' connaissances+=[Connaissance]+)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'connaissancesDonne'
		public Keyword getConnaissancesDonneKeyword_5_0() { return cConnaissancesDonneKeyword_5_0; }
		
		//connaissances+=[Connaissance]+
		public Assignment getConnaissancesAssignment_5_1() { return cConnaissancesAssignment_5_1; }
		
		//[Connaissance]
		public CrossReference getConnaissancesConnaissanceCrossReference_5_1_0() { return cConnaissancesConnaissanceCrossReference_5_1_0; }
		
		//ID
		public RuleCall getConnaissancesConnaissanceIDTerminalRuleCall_5_1_0_1() { return cConnaissancesConnaissanceIDTerminalRuleCall_5_1_0_1; }
		
		//conditions+=Condition*
		public Assignment getConditionsAssignment_6() { return cConditionsAssignment_6; }
		
		//Condition
		public RuleCall getConditionsConditionParserRuleCall_6_0() { return cConditionsConditionParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class ObjetElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.enseeiht.GAME.Objet");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cObjetKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDescriptionsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDescriptionsDescriptionParserRuleCall_3_0 = (RuleCall)cDescriptionsAssignment_3.eContents().get(0);
		private final Keyword cTailleKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTailleAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTailleINTTerminalRuleCall_5_0 = (RuleCall)cTailleAssignment_5.eContents().get(0);
		private final Assignment cVisibiliteAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cVisibiliteVisibiliteEnumRuleCall_6_0 = (RuleCall)cVisibiliteAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cSiKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cConditionsVisibiliteAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cConditionsVisibiliteConditionParserRuleCall_7_1_0 = (RuleCall)cConditionsVisibiliteAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Objet:
		//	'objet' name=ID '{'
		//	descriptions+=Description?
		//	'taille' taille=INT
		//	visibilite=Visibilite ('si' conditionsVisibilite=Condition)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'objet' name=ID '{' descriptions+=Description? 'taille' taille=INT visibilite=Visibilite ('si'
		//conditionsVisibilite=Condition)? '}'
		public Group getGroup() { return cGroup; }
		
		//'objet'
		public Keyword getObjetKeyword_0() { return cObjetKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//descriptions+=Description?
		public Assignment getDescriptionsAssignment_3() { return cDescriptionsAssignment_3; }
		
		//Description
		public RuleCall getDescriptionsDescriptionParserRuleCall_3_0() { return cDescriptionsDescriptionParserRuleCall_3_0; }
		
		//'taille'
		public Keyword getTailleKeyword_4() { return cTailleKeyword_4; }
		
		//taille=INT
		public Assignment getTailleAssignment_5() { return cTailleAssignment_5; }
		
		//INT
		public RuleCall getTailleINTTerminalRuleCall_5_0() { return cTailleINTTerminalRuleCall_5_0; }
		
		//visibilite=Visibilite
		public Assignment getVisibiliteAssignment_6() { return cVisibiliteAssignment_6; }
		
		//Visibilite
		public RuleCall getVisibiliteVisibiliteEnumRuleCall_6_0() { return cVisibiliteVisibiliteEnumRuleCall_6_0; }
		
		//('si' conditionsVisibilite=Condition)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'si'
		public Keyword getSiKeyword_7_0() { return cSiKeyword_7_0; }
		
		//conditionsVisibilite=Condition
		public Assignment getConditionsVisibiliteAssignment_7_1() { return cConditionsVisibiliteAssignment_7_1; }
		
		//Condition
		public RuleCall getConditionsVisibiliteConditionParserRuleCall_7_1_0() { return cConditionsVisibiliteConditionParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class DescriptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.enseeiht.GAME.Description");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDescriptionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTextAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTextSTRINGTerminalRuleCall_2_0 = (RuleCall)cTextAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Description:
		//	'description' '{'
		//	text=STRING
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'description' '{' text=STRING '}'
		public Group getGroup() { return cGroup; }
		
		//'description'
		public Keyword getDescriptionKeyword_0() { return cDescriptionKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//text=STRING
		public Assignment getTextAssignment_2() { return cTextAssignment_2; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_2_0() { return cTextSTRINGTerminalRuleCall_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class ConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.enseeiht.GAME.Condition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConditionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cObjetsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cNecessairesKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cObjetsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final CrossReference cObjetsObjetCrossReference_3_2_0 = (CrossReference)cObjetsAssignment_3_2.eContents().get(0);
		private final RuleCall cObjetsObjetIDTerminalRuleCall_3_2_0_1 = (RuleCall)cObjetsObjetCrossReference_3_2_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cObjetsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cManquantsKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cObjetsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cObjetsObjetCrossReference_4_2_0 = (CrossReference)cObjetsAssignment_4_2.eContents().get(0);
		private final RuleCall cObjetsObjetIDTerminalRuleCall_4_2_0_1 = (RuleCall)cObjetsObjetCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cConnaissancesKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cNecessairesKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cConnaissancesAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cConnaissancesConnaissanceCrossReference_5_2_0 = (CrossReference)cConnaissancesAssignment_5_2.eContents().get(0);
		private final RuleCall cConnaissancesConnaissanceIDTerminalRuleCall_5_2_0_1 = (RuleCall)cConnaissancesConnaissanceCrossReference_5_2_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Condition:
		//	'condition' name=ID '{' ('objets' 'necessaires' objets+=[Objet]*)? ('objets' 'manquants' objets+=[Objet]*)?
		//	('connaissances' 'necessaires' connaissances+=[Connaissance]*)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'condition' name=ID '{' ('objets' 'necessaires' objets+=[Objet]*)? ('objets' 'manquants' objets+=[Objet]*)?
		//('connaissances' 'necessaires' connaissances+=[Connaissance]*)? '}'
		public Group getGroup() { return cGroup; }
		
		//'condition'
		public Keyword getConditionKeyword_0() { return cConditionKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('objets' 'necessaires' objets+=[Objet]*)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'objets'
		public Keyword getObjetsKeyword_3_0() { return cObjetsKeyword_3_0; }
		
		//'necessaires'
		public Keyword getNecessairesKeyword_3_1() { return cNecessairesKeyword_3_1; }
		
		//objets+=[Objet]*
		public Assignment getObjetsAssignment_3_2() { return cObjetsAssignment_3_2; }
		
		//[Objet]
		public CrossReference getObjetsObjetCrossReference_3_2_0() { return cObjetsObjetCrossReference_3_2_0; }
		
		//ID
		public RuleCall getObjetsObjetIDTerminalRuleCall_3_2_0_1() { return cObjetsObjetIDTerminalRuleCall_3_2_0_1; }
		
		//('objets' 'manquants' objets+=[Objet]*)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'objets'
		public Keyword getObjetsKeyword_4_0() { return cObjetsKeyword_4_0; }
		
		//'manquants'
		public Keyword getManquantsKeyword_4_1() { return cManquantsKeyword_4_1; }
		
		//objets+=[Objet]*
		public Assignment getObjetsAssignment_4_2() { return cObjetsAssignment_4_2; }
		
		//[Objet]
		public CrossReference getObjetsObjetCrossReference_4_2_0() { return cObjetsObjetCrossReference_4_2_0; }
		
		//ID
		public RuleCall getObjetsObjetIDTerminalRuleCall_4_2_0_1() { return cObjetsObjetIDTerminalRuleCall_4_2_0_1; }
		
		//('connaissances' 'necessaires' connaissances+=[Connaissance]*)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'connaissances'
		public Keyword getConnaissancesKeyword_5_0() { return cConnaissancesKeyword_5_0; }
		
		//'necessaires'
		public Keyword getNecessairesKeyword_5_1() { return cNecessairesKeyword_5_1; }
		
		//connaissances+=[Connaissance]*
		public Assignment getConnaissancesAssignment_5_2() { return cConnaissancesAssignment_5_2; }
		
		//[Connaissance]
		public CrossReference getConnaissancesConnaissanceCrossReference_5_2_0() { return cConnaissancesConnaissanceCrossReference_5_2_0; }
		
		//ID
		public RuleCall getConnaissancesConnaissanceIDTerminalRuleCall_5_2_0_1() { return cConnaissancesConnaissanceIDTerminalRuleCall_5_2_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ConnaissanceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.enseeiht.GAME.Connaissance");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConnaissanceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDescriptionsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDescriptionsDescriptionParserRuleCall_3_0 = (RuleCall)cDescriptionsAssignment_3.eContents().get(0);
		private final Assignment cVisibiliteAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cVisibiliteVisibiliteEnumRuleCall_4_0 = (RuleCall)cVisibiliteAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cSiKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cConditionsVisibiliteAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cConditionsVisibiliteConditionParserRuleCall_5_1_0 = (RuleCall)cConditionsVisibiliteAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Connaissance:
		//	'connaissance' name=ID '{'
		//	descriptions+=Description?
		//	visibilite=Visibilite ('si' conditionsVisibilite=Condition)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'connaissance' name=ID '{' descriptions+=Description? visibilite=Visibilite ('si' conditionsVisibilite=Condition)? '}'
		public Group getGroup() { return cGroup; }
		
		//'connaissance'
		public Keyword getConnaissanceKeyword_0() { return cConnaissanceKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//descriptions+=Description?
		public Assignment getDescriptionsAssignment_3() { return cDescriptionsAssignment_3; }
		
		//Description
		public RuleCall getDescriptionsDescriptionParserRuleCall_3_0() { return cDescriptionsDescriptionParserRuleCall_3_0; }
		
		//visibilite=Visibilite
		public Assignment getVisibiliteAssignment_4() { return cVisibiliteAssignment_4; }
		
		//Visibilite
		public RuleCall getVisibiliteVisibiliteEnumRuleCall_4_0() { return cVisibiliteVisibiliteEnumRuleCall_4_0; }
		
		//('si' conditionsVisibilite=Condition)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'si'
		public Keyword getSiKeyword_5_0() { return cSiKeyword_5_0; }
		
		//conditionsVisibilite=Condition
		public Assignment getConditionsVisibiliteAssignment_5_1() { return cConditionsVisibiliteAssignment_5_1; }
		
		//Condition
		public RuleCall getConditionsVisibiliteConditionParserRuleCall_5_1_0() { return cConditionsVisibiliteConditionParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ExplorateurElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.enseeiht.GAME.Explorateur");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cExplorateurKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTailleKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTailleAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTailleINTTerminalRuleCall_4_0 = (RuleCall)cTailleAssignment_4.eContents().get(0);
		private final Keyword cInventaireOKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cObjetsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cObjetsObjetAvecQuantiteCrossReference_6_0 = (CrossReference)cObjetsAssignment_6.eContents().get(0);
		private final RuleCall cObjetsObjetAvecQuantiteIDTerminalRuleCall_6_0_1 = (RuleCall)cObjetsObjetAvecQuantiteCrossReference_6_0.eContents().get(1);
		private final Keyword cInventaireCKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cConnaissancesAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cConnaissancesConnaissanceCrossReference_8_0 = (CrossReference)cConnaissancesAssignment_8.eContents().get(0);
		private final RuleCall cConnaissancesConnaissanceIDTerminalRuleCall_8_0_1 = (RuleCall)cConnaissancesConnaissanceCrossReference_8_0.eContents().get(1);
		private final Keyword cLocalisationKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cLocalisationAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final CrossReference cLocalisationLieuCrossReference_10_0 = (CrossReference)cLocalisationAssignment_10.eContents().get(0);
		private final RuleCall cLocalisationLieuIDTerminalRuleCall_10_0_1 = (RuleCall)cLocalisationLieuCrossReference_10_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Explorateur:
		//	'explorateur' name=ID '{'
		//	'taille' taille=INT
		//	'inventaireO' objets+=[ObjetAvecQuantite]*
		//	'inventaireC' connaissances+=[Connaissance]*
		//	'localisation' localisation=[Lieu]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'explorateur' name=ID '{' 'taille' taille=INT 'inventaireO' objets+=[ObjetAvecQuantite]* 'inventaireC'
		//connaissances+=[Connaissance]* 'localisation' localisation=[Lieu] '}'
		public Group getGroup() { return cGroup; }
		
		//'explorateur'
		public Keyword getExplorateurKeyword_0() { return cExplorateurKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'taille'
		public Keyword getTailleKeyword_3() { return cTailleKeyword_3; }
		
		//taille=INT
		public Assignment getTailleAssignment_4() { return cTailleAssignment_4; }
		
		//INT
		public RuleCall getTailleINTTerminalRuleCall_4_0() { return cTailleINTTerminalRuleCall_4_0; }
		
		//'inventaireO'
		public Keyword getInventaireOKeyword_5() { return cInventaireOKeyword_5; }
		
		//objets+=[ObjetAvecQuantite]*
		public Assignment getObjetsAssignment_6() { return cObjetsAssignment_6; }
		
		//[ObjetAvecQuantite]
		public CrossReference getObjetsObjetAvecQuantiteCrossReference_6_0() { return cObjetsObjetAvecQuantiteCrossReference_6_0; }
		
		//ID
		public RuleCall getObjetsObjetAvecQuantiteIDTerminalRuleCall_6_0_1() { return cObjetsObjetAvecQuantiteIDTerminalRuleCall_6_0_1; }
		
		//'inventaireC'
		public Keyword getInventaireCKeyword_7() { return cInventaireCKeyword_7; }
		
		//connaissances+=[Connaissance]*
		public Assignment getConnaissancesAssignment_8() { return cConnaissancesAssignment_8; }
		
		//[Connaissance]
		public CrossReference getConnaissancesConnaissanceCrossReference_8_0() { return cConnaissancesConnaissanceCrossReference_8_0; }
		
		//ID
		public RuleCall getConnaissancesConnaissanceIDTerminalRuleCall_8_0_1() { return cConnaissancesConnaissanceIDTerminalRuleCall_8_0_1; }
		
		//'localisation'
		public Keyword getLocalisationKeyword_9() { return cLocalisationKeyword_9; }
		
		//localisation=[Lieu]
		public Assignment getLocalisationAssignment_10() { return cLocalisationAssignment_10; }
		
		//[Lieu]
		public CrossReference getLocalisationLieuCrossReference_10_0() { return cLocalisationLieuCrossReference_10_0; }
		
		//ID
		public RuleCall getLocalisationLieuIDTerminalRuleCall_10_0_1() { return cLocalisationLieuIDTerminalRuleCall_10_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class ObjetAvecQuantiteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.enseeiht.GAME.ObjetAvecQuantite");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cObjetavecquantiteKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cObjetAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cObjetObjetCrossReference_3_0 = (CrossReference)cObjetAssignment_3.eContents().get(0);
		private final RuleCall cObjetObjetIDTerminalRuleCall_3_0_1 = (RuleCall)cObjetObjetCrossReference_3_0.eContents().get(1);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cQuantiteAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cQuantiteINTTerminalRuleCall_5_0 = (RuleCall)cQuantiteAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//ObjetAvecQuantite:
		//	'objetavecquantite' name=ID '{'
		//	objet=[Objet] "," quantite=INT
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'objetavecquantite' name=ID '{' objet=[Objet] "," quantite=INT '}'
		public Group getGroup() { return cGroup; }
		
		//'objetavecquantite'
		public Keyword getObjetavecquantiteKeyword_0() { return cObjetavecquantiteKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//objet=[Objet]
		public Assignment getObjetAssignment_3() { return cObjetAssignment_3; }
		
		//[Objet]
		public CrossReference getObjetObjetCrossReference_3_0() { return cObjetObjetCrossReference_3_0; }
		
		//ID
		public RuleCall getObjetObjetIDTerminalRuleCall_3_0_1() { return cObjetObjetIDTerminalRuleCall_3_0_1; }
		
		//","
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }
		
		//quantite=INT
		public Assignment getQuantiteAssignment_5() { return cQuantiteAssignment_5; }
		
		//INT
		public RuleCall getQuantiteINTTerminalRuleCall_5_0() { return cQuantiteINTTerminalRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class LieuElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.enseeiht.GAME.Lieu");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLieuKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDescriptionsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDescriptionsDescriptionParserRuleCall_3_0 = (RuleCall)cDescriptionsAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cObjetsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cTrouvablesKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cObjetsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cObjetsObjetCrossReference_4_2_0 = (CrossReference)cObjetsAssignment_4_2.eContents().get(0);
		private final RuleCall cObjetsObjetIDTerminalRuleCall_4_2_0_1 = (RuleCall)cObjetsObjetCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cConnaissancesKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cTrouvableKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cConnaissancesAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cConnaissancesConnaissanceCrossReference_5_2_0 = (CrossReference)cConnaissancesAssignment_5_2.eContents().get(0);
		private final RuleCall cConnaissancesConnaissanceIDTerminalRuleCall_5_2_0_1 = (RuleCall)cConnaissancesConnaissanceCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cPersonnesKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cTrouvableKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cPersonnesAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cPersonnesPersonneCrossReference_6_2_0 = (CrossReference)cPersonnesAssignment_6_2.eContents().get(0);
		private final RuleCall cPersonnesPersonneIDTerminalRuleCall_6_2_0_1 = (RuleCall)cPersonnesPersonneCrossReference_6_2_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCheminspossibleKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cCheminspossibleAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cCheminspossibleCheminCrossReference_7_1_0 = (CrossReference)cCheminspossibleAssignment_7_1.eContents().get(0);
		private final RuleCall cCheminspossibleCheminIDTerminalRuleCall_7_1_0_1 = (RuleCall)cCheminspossibleCheminCrossReference_7_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Lieu:
		//	'lieu' name=ID '{'
		//	descriptions+=Description? ('objets' 'trouvables' objets+=[Objet])* ('connaissances' 'trouvable'
		//	connaissances+=[Connaissance])* ('personnes' 'trouvable' personnes+=[Personne])* ('cheminspossible'
		//	cheminspossible+=[Chemin]+)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'lieu' name=ID '{' descriptions+=Description? ('objets' 'trouvables' objets+=[Objet])* ('connaissances' 'trouvable'
		//connaissances+=[Connaissance])* ('personnes' 'trouvable' personnes+=[Personne])* ('cheminspossible'
		//cheminspossible+=[Chemin]+)? '}'
		public Group getGroup() { return cGroup; }
		
		//'lieu'
		public Keyword getLieuKeyword_0() { return cLieuKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//descriptions+=Description?
		public Assignment getDescriptionsAssignment_3() { return cDescriptionsAssignment_3; }
		
		//Description
		public RuleCall getDescriptionsDescriptionParserRuleCall_3_0() { return cDescriptionsDescriptionParserRuleCall_3_0; }
		
		//('objets' 'trouvables' objets+=[Objet])*
		public Group getGroup_4() { return cGroup_4; }
		
		//'objets'
		public Keyword getObjetsKeyword_4_0() { return cObjetsKeyword_4_0; }
		
		//'trouvables'
		public Keyword getTrouvablesKeyword_4_1() { return cTrouvablesKeyword_4_1; }
		
		//objets+=[Objet]
		public Assignment getObjetsAssignment_4_2() { return cObjetsAssignment_4_2; }
		
		//[Objet]
		public CrossReference getObjetsObjetCrossReference_4_2_0() { return cObjetsObjetCrossReference_4_2_0; }
		
		//ID
		public RuleCall getObjetsObjetIDTerminalRuleCall_4_2_0_1() { return cObjetsObjetIDTerminalRuleCall_4_2_0_1; }
		
		//('connaissances' 'trouvable' connaissances+=[Connaissance])*
		public Group getGroup_5() { return cGroup_5; }
		
		//'connaissances'
		public Keyword getConnaissancesKeyword_5_0() { return cConnaissancesKeyword_5_0; }
		
		//'trouvable'
		public Keyword getTrouvableKeyword_5_1() { return cTrouvableKeyword_5_1; }
		
		//connaissances+=[Connaissance]
		public Assignment getConnaissancesAssignment_5_2() { return cConnaissancesAssignment_5_2; }
		
		//[Connaissance]
		public CrossReference getConnaissancesConnaissanceCrossReference_5_2_0() { return cConnaissancesConnaissanceCrossReference_5_2_0; }
		
		//ID
		public RuleCall getConnaissancesConnaissanceIDTerminalRuleCall_5_2_0_1() { return cConnaissancesConnaissanceIDTerminalRuleCall_5_2_0_1; }
		
		//('personnes' 'trouvable' personnes+=[Personne])*
		public Group getGroup_6() { return cGroup_6; }
		
		//'personnes'
		public Keyword getPersonnesKeyword_6_0() { return cPersonnesKeyword_6_0; }
		
		//'trouvable'
		public Keyword getTrouvableKeyword_6_1() { return cTrouvableKeyword_6_1; }
		
		//personnes+=[Personne]
		public Assignment getPersonnesAssignment_6_2() { return cPersonnesAssignment_6_2; }
		
		//[Personne]
		public CrossReference getPersonnesPersonneCrossReference_6_2_0() { return cPersonnesPersonneCrossReference_6_2_0; }
		
		//ID
		public RuleCall getPersonnesPersonneIDTerminalRuleCall_6_2_0_1() { return cPersonnesPersonneIDTerminalRuleCall_6_2_0_1; }
		
		//('cheminspossible' cheminspossible+=[Chemin]+)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'cheminspossible'
		public Keyword getCheminspossibleKeyword_7_0() { return cCheminspossibleKeyword_7_0; }
		
		//cheminspossible+=[Chemin]+
		public Assignment getCheminspossibleAssignment_7_1() { return cCheminspossibleAssignment_7_1; }
		
		//[Chemin]
		public CrossReference getCheminspossibleCheminCrossReference_7_1_0() { return cCheminspossibleCheminCrossReference_7_1_0; }
		
		//ID
		public RuleCall getCheminspossibleCheminIDTerminalRuleCall_7_1_0_1() { return cCheminspossibleCheminIDTerminalRuleCall_7_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	
	public class VisibiliteElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "fr.enseeiht.GAME.Visibilite");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cVisibleEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cVisibleVisibleKeyword_0_0 = (Keyword)cVisibleEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cInvisibleEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cInvisibleInvisibleKeyword_1_0 = (Keyword)cInvisibleEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum Visibilite:
		//	Visible='visible'
		//	| Invisible='invisible';
		public EnumRule getRule() { return rule; }
		
		//Visible='visible' | Invisible='invisible'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Visible='visible'
		public EnumLiteralDeclaration getVisibleEnumLiteralDeclaration_0() { return cVisibleEnumLiteralDeclaration_0; }
		
		//'visible'
		public Keyword getVisibleVisibleKeyword_0_0() { return cVisibleVisibleKeyword_0_0; }
		
		//Invisible='invisible'
		public EnumLiteralDeclaration getInvisibleEnumLiteralDeclaration_1() { return cInvisibleEnumLiteralDeclaration_1; }
		
		//'invisible'
		public Keyword getInvisibleInvisibleKeyword_1_0() { return cInvisibleInvisibleKeyword_1_0; }
	}
	public class OuvertureElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "fr.enseeiht.GAME.Ouverture");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cOuvertEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cOuvertOuvertKeyword_0_0 = (Keyword)cOuvertEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cFermeEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cFermeFermeKeyword_1_0 = (Keyword)cFermeEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum Ouverture:
		//	Ouvert='ouvert'
		//	| Ferme='ferme';
		public EnumRule getRule() { return rule; }
		
		//Ouvert='ouvert' | Ferme='ferme'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Ouvert='ouvert'
		public EnumLiteralDeclaration getOuvertEnumLiteralDeclaration_0() { return cOuvertEnumLiteralDeclaration_0; }
		
		//'ouvert'
		public Keyword getOuvertOuvertKeyword_0_0() { return cOuvertOuvertKeyword_0_0; }
		
		//Ferme='ferme'
		public EnumLiteralDeclaration getFermeEnumLiteralDeclaration_1() { return cFermeEnumLiteralDeclaration_1; }
		
		//'ferme'
		public Keyword getFermeFermeKeyword_1_0() { return cFermeFermeKeyword_1_0; }
	}
	
	private final JeuElements pJeu;
	private final CheminElements pChemin;
	private final PersonneElements pPersonne;
	private final InteractionElements pInteraction;
	private final ChoixElements pChoix;
	private final ActionElements pAction;
	private final EchangeElements pEchange;
	private final ObjetElements pObjet;
	private final DescriptionElements pDescription;
	private final ConditionElements pCondition;
	private final ConnaissanceElements pConnaissance;
	private final ExplorateurElements pExplorateur;
	private final ObjetAvecQuantiteElements pObjetAvecQuantite;
	private final LieuElements pLieu;
	private final VisibiliteElements eVisibilite;
	private final OuvertureElements eOuverture;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public GAMEGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pJeu = new JeuElements();
		this.pChemin = new CheminElements();
		this.pPersonne = new PersonneElements();
		this.pInteraction = new InteractionElements();
		this.pChoix = new ChoixElements();
		this.pAction = new ActionElements();
		this.pEchange = new EchangeElements();
		this.pObjet = new ObjetElements();
		this.pDescription = new DescriptionElements();
		this.pCondition = new ConditionElements();
		this.pConnaissance = new ConnaissanceElements();
		this.pExplorateur = new ExplorateurElements();
		this.pObjetAvecQuantite = new ObjetAvecQuantiteElements();
		this.pLieu = new LieuElements();
		this.eVisibilite = new VisibiliteElements();
		this.eOuverture = new OuvertureElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fr.enseeiht.GAME".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Jeu:
	//	'jeu' name=ID '{'
	//	explorateur=Explorateur
	//	'pointDepart' pointDepart=[Lieu]
	//	'pointFin' pointFin+=[Lieu]+
	//	lieux+=Lieu*
	//	Objets+=Objet*
	//	ObjetAvecQuantite+=ObjetAvecQuantite*
	//	Connaissances+=Connaissance*
	//	personnes+=Personne*
	//	chemins+=Chemin*
	//	'}';
	public JeuElements getJeuAccess() {
		return pJeu;
	}
	
	public ParserRule getJeuRule() {
		return getJeuAccess().getRule();
	}
	
	//Chemin:
	//	'chemin' name=ID '{'
	//	descriptions=Description?
	//	'de' depart=[Lieu]
	//	'vers' arrive=[Lieu] visibilite=Visibilite ('si' conditionsVisibilite=Condition)?
	//	ouverture=Ouverture ('si' conditionsOuverture=Condition)?
	//	'}';
	public CheminElements getCheminAccess() {
		return pChemin;
	}
	
	public ParserRule getCheminRule() {
		return getCheminAccess().getRule();
	}
	
	//Personne:
	//	'personne' name=ID '{'
	//	descriptions=Description
	//	interaction=Interaction
	//	visibilite=Visibilite ('si' conditionsVisibilite=Condition)?
	//	'}';
	public PersonneElements getPersonneAccess() {
		return pPersonne;
	}
	
	public ParserRule getPersonneRule() {
		return getPersonneAccess().getRule();
	}
	
	//Interaction:
	//	'interaction' '{'
	//	echanges+=Echange*
	//	choix+=Choix+
	//	'}';
	public InteractionElements getInteractionAccess() {
		return pInteraction;
	}
	
	public ParserRule getInteractionRule() {
		return getInteractionAccess().getRule();
	}
	
	//Choix:
	//	'choix' name=ID '{'
	//	actions+=Action*
	//	conditions+=Condition*
	//	'}';
	public ChoixElements getChoixAccess() {
		return pChoix;
	}
	
	public ParserRule getChoixRule() {
		return getChoixAccess().getRule();
	}
	
	//Action:
	//	'action' name=ID '{'
	//	descriptions+=Description conditions+=Condition*
	//	echanges+=Echange+
	//	'}';
	public ActionElements getActionAccess() {
		return pAction;
	}
	
	public ParserRule getActionRule() {
		return getActionAccess().getRule();
	}
	
	//Echange:
	//	{Echange} 'echange' '{' ('objetsDonne' objetsDonne+=[Objet]+)? ('objetsPris' objetsPris+=[Objet]+)?
	//	('connaissancesDonne' connaissances+=[Connaissance]+)?
	//	conditions+=Condition*
	//	'}';
	public EchangeElements getEchangeAccess() {
		return pEchange;
	}
	
	public ParserRule getEchangeRule() {
		return getEchangeAccess().getRule();
	}
	
	//Objet:
	//	'objet' name=ID '{'
	//	descriptions+=Description?
	//	'taille' taille=INT
	//	visibilite=Visibilite ('si' conditionsVisibilite=Condition)?
	//	'}';
	public ObjetElements getObjetAccess() {
		return pObjet;
	}
	
	public ParserRule getObjetRule() {
		return getObjetAccess().getRule();
	}
	
	//Description:
	//	'description' '{'
	//	text=STRING
	//	'}';
	public DescriptionElements getDescriptionAccess() {
		return pDescription;
	}
	
	public ParserRule getDescriptionRule() {
		return getDescriptionAccess().getRule();
	}
	
	//Condition:
	//	'condition' name=ID '{' ('objets' 'necessaires' objets+=[Objet]*)? ('objets' 'manquants' objets+=[Objet]*)?
	//	('connaissances' 'necessaires' connaissances+=[Connaissance]*)?
	//	'}';
	public ConditionElements getConditionAccess() {
		return pCondition;
	}
	
	public ParserRule getConditionRule() {
		return getConditionAccess().getRule();
	}
	
	//Connaissance:
	//	'connaissance' name=ID '{'
	//	descriptions+=Description?
	//	visibilite=Visibilite ('si' conditionsVisibilite=Condition)?
	//	'}';
	public ConnaissanceElements getConnaissanceAccess() {
		return pConnaissance;
	}
	
	public ParserRule getConnaissanceRule() {
		return getConnaissanceAccess().getRule();
	}
	
	//Explorateur:
	//	'explorateur' name=ID '{'
	//	'taille' taille=INT
	//	'inventaireO' objets+=[ObjetAvecQuantite]*
	//	'inventaireC' connaissances+=[Connaissance]*
	//	'localisation' localisation=[Lieu]
	//	'}';
	public ExplorateurElements getExplorateurAccess() {
		return pExplorateur;
	}
	
	public ParserRule getExplorateurRule() {
		return getExplorateurAccess().getRule();
	}
	
	//ObjetAvecQuantite:
	//	'objetavecquantite' name=ID '{'
	//	objet=[Objet] "," quantite=INT
	//	'}';
	public ObjetAvecQuantiteElements getObjetAvecQuantiteAccess() {
		return pObjetAvecQuantite;
	}
	
	public ParserRule getObjetAvecQuantiteRule() {
		return getObjetAvecQuantiteAccess().getRule();
	}
	
	//Lieu:
	//	'lieu' name=ID '{'
	//	descriptions+=Description? ('objets' 'trouvables' objets+=[Objet])* ('connaissances' 'trouvable'
	//	connaissances+=[Connaissance])* ('personnes' 'trouvable' personnes+=[Personne])* ('cheminspossible'
	//	cheminspossible+=[Chemin]+)?
	//	'}';
	public LieuElements getLieuAccess() {
		return pLieu;
	}
	
	public ParserRule getLieuRule() {
		return getLieuAccess().getRule();
	}
	
	//enum Visibilite:
	//	Visible='visible'
	//	| Invisible='invisible';
	public VisibiliteElements getVisibiliteAccess() {
		return eVisibilite;
	}
	
	public EnumRule getVisibiliteRule() {
		return getVisibiliteAccess().getRule();
	}
	
	//enum Ouverture:
	//	Ouvert='ouvert'
	//	| Ferme='ferme';
	public OuvertureElements getOuvertureAccess() {
		return eOuverture;
	}
	
	public EnumRule getOuvertureRule() {
		return getOuvertureAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
