/*
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractGAMEValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(fr.enseeiht.gAME.GAMEPackage.eINSTANCE);
		return result;
	}
}
