/**
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.validation;

import fr.enseeiht.validation.AbstractGAMEValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GAMEValidator extends AbstractGAMEValidator {
}
