/**
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.gAME.impl;

import fr.enseeiht.gAME.Chemin;
import fr.enseeiht.gAME.Condition;
import fr.enseeiht.gAME.Description;
import fr.enseeiht.gAME.GAMEPackage;
import fr.enseeiht.gAME.Lieu;
import fr.enseeiht.gAME.Visibilite;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Chemin</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.gAME.impl.CheminImpl#getName <em>Name</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.impl.CheminImpl#getDescriptions <em>Descriptions</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.impl.CheminImpl#getDepart <em>Depart</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.impl.CheminImpl#getArrive <em>Arrive</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.impl.CheminImpl#getVisibilite <em>Visibilite</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.impl.CheminImpl#getConditionsVisibilite <em>Conditions Visibilite</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CheminImpl extends MinimalEObjectImpl.Container implements Chemin
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getDescriptions() <em>Descriptions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescriptions()
   * @generated
   * @ordered
   */
  protected Description descriptions;

  /**
   * The cached value of the '{@link #getDepart() <em>Depart</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDepart()
   * @generated
   * @ordered
   */
  protected Lieu depart;

  /**
   * The cached value of the '{@link #getArrive() <em>Arrive</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArrive()
   * @generated
   * @ordered
   */
  protected Lieu arrive;

  /**
   * The default value of the '{@link #getVisibilite() <em>Visibilite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVisibilite()
   * @generated
   * @ordered
   */
  protected static final Visibilite VISIBILITE_EDEFAULT = Visibilite.VISIBLE;

  /**
   * The cached value of the '{@link #getVisibilite() <em>Visibilite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVisibilite()
   * @generated
   * @ordered
   */
  protected Visibilite visibilite = VISIBILITE_EDEFAULT;

  /**
   * The cached value of the '{@link #getConditionsVisibilite() <em>Conditions Visibilite</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConditionsVisibilite()
   * @generated
   * @ordered
   */
  protected Condition conditionsVisibilite;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CheminImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GAMEPackage.Literals.CHEMIN;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GAMEPackage.CHEMIN__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Description getDescriptions()
  {
    return descriptions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDescriptions(Description newDescriptions, NotificationChain msgs)
  {
    Description oldDescriptions = descriptions;
    descriptions = newDescriptions;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GAMEPackage.CHEMIN__DESCRIPTIONS, oldDescriptions, newDescriptions);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDescriptions(Description newDescriptions)
  {
    if (newDescriptions != descriptions)
    {
      NotificationChain msgs = null;
      if (descriptions != null)
        msgs = ((InternalEObject)descriptions).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GAMEPackage.CHEMIN__DESCRIPTIONS, null, msgs);
      if (newDescriptions != null)
        msgs = ((InternalEObject)newDescriptions).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GAMEPackage.CHEMIN__DESCRIPTIONS, null, msgs);
      msgs = basicSetDescriptions(newDescriptions, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GAMEPackage.CHEMIN__DESCRIPTIONS, newDescriptions, newDescriptions));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Lieu getDepart()
  {
    if (depart != null && depart.eIsProxy())
    {
      InternalEObject oldDepart = (InternalEObject)depart;
      depart = (Lieu)eResolveProxy(oldDepart);
      if (depart != oldDepart)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, GAMEPackage.CHEMIN__DEPART, oldDepart, depart));
      }
    }
    return depart;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Lieu basicGetDepart()
  {
    return depart;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDepart(Lieu newDepart)
  {
    Lieu oldDepart = depart;
    depart = newDepart;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GAMEPackage.CHEMIN__DEPART, oldDepart, depart));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Lieu getArrive()
  {
    if (arrive != null && arrive.eIsProxy())
    {
      InternalEObject oldArrive = (InternalEObject)arrive;
      arrive = (Lieu)eResolveProxy(oldArrive);
      if (arrive != oldArrive)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, GAMEPackage.CHEMIN__ARRIVE, oldArrive, arrive));
      }
    }
    return arrive;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Lieu basicGetArrive()
  {
    return arrive;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setArrive(Lieu newArrive)
  {
    Lieu oldArrive = arrive;
    arrive = newArrive;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GAMEPackage.CHEMIN__ARRIVE, oldArrive, arrive));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Visibilite getVisibilite()
  {
    return visibilite;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVisibilite(Visibilite newVisibilite)
  {
    Visibilite oldVisibilite = visibilite;
    visibilite = newVisibilite == null ? VISIBILITE_EDEFAULT : newVisibilite;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GAMEPackage.CHEMIN__VISIBILITE, oldVisibilite, visibilite));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Condition getConditionsVisibilite()
  {
    return conditionsVisibilite;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetConditionsVisibilite(Condition newConditionsVisibilite, NotificationChain msgs)
  {
    Condition oldConditionsVisibilite = conditionsVisibilite;
    conditionsVisibilite = newConditionsVisibilite;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GAMEPackage.CHEMIN__CONDITIONS_VISIBILITE, oldConditionsVisibilite, newConditionsVisibilite);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setConditionsVisibilite(Condition newConditionsVisibilite)
  {
    if (newConditionsVisibilite != conditionsVisibilite)
    {
      NotificationChain msgs = null;
      if (conditionsVisibilite != null)
        msgs = ((InternalEObject)conditionsVisibilite).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GAMEPackage.CHEMIN__CONDITIONS_VISIBILITE, null, msgs);
      if (newConditionsVisibilite != null)
        msgs = ((InternalEObject)newConditionsVisibilite).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GAMEPackage.CHEMIN__CONDITIONS_VISIBILITE, null, msgs);
      msgs = basicSetConditionsVisibilite(newConditionsVisibilite, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GAMEPackage.CHEMIN__CONDITIONS_VISIBILITE, newConditionsVisibilite, newConditionsVisibilite));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GAMEPackage.CHEMIN__DESCRIPTIONS:
        return basicSetDescriptions(null, msgs);
      case GAMEPackage.CHEMIN__CONDITIONS_VISIBILITE:
        return basicSetConditionsVisibilite(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GAMEPackage.CHEMIN__NAME:
        return getName();
      case GAMEPackage.CHEMIN__DESCRIPTIONS:
        return getDescriptions();
      case GAMEPackage.CHEMIN__DEPART:
        if (resolve) return getDepart();
        return basicGetDepart();
      case GAMEPackage.CHEMIN__ARRIVE:
        if (resolve) return getArrive();
        return basicGetArrive();
      case GAMEPackage.CHEMIN__VISIBILITE:
        return getVisibilite();
      case GAMEPackage.CHEMIN__CONDITIONS_VISIBILITE:
        return getConditionsVisibilite();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GAMEPackage.CHEMIN__NAME:
        setName((String)newValue);
        return;
      case GAMEPackage.CHEMIN__DESCRIPTIONS:
        setDescriptions((Description)newValue);
        return;
      case GAMEPackage.CHEMIN__DEPART:
        setDepart((Lieu)newValue);
        return;
      case GAMEPackage.CHEMIN__ARRIVE:
        setArrive((Lieu)newValue);
        return;
      case GAMEPackage.CHEMIN__VISIBILITE:
        setVisibilite((Visibilite)newValue);
        return;
      case GAMEPackage.CHEMIN__CONDITIONS_VISIBILITE:
        setConditionsVisibilite((Condition)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GAMEPackage.CHEMIN__NAME:
        setName(NAME_EDEFAULT);
        return;
      case GAMEPackage.CHEMIN__DESCRIPTIONS:
        setDescriptions((Description)null);
        return;
      case GAMEPackage.CHEMIN__DEPART:
        setDepart((Lieu)null);
        return;
      case GAMEPackage.CHEMIN__ARRIVE:
        setArrive((Lieu)null);
        return;
      case GAMEPackage.CHEMIN__VISIBILITE:
        setVisibilite(VISIBILITE_EDEFAULT);
        return;
      case GAMEPackage.CHEMIN__CONDITIONS_VISIBILITE:
        setConditionsVisibilite((Condition)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GAMEPackage.CHEMIN__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case GAMEPackage.CHEMIN__DESCRIPTIONS:
        return descriptions != null;
      case GAMEPackage.CHEMIN__DEPART:
        return depart != null;
      case GAMEPackage.CHEMIN__ARRIVE:
        return arrive != null;
      case GAMEPackage.CHEMIN__VISIBILITE:
        return visibilite != VISIBILITE_EDEFAULT;
      case GAMEPackage.CHEMIN__CONDITIONS_VISIBILITE:
        return conditionsVisibilite != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", visibilite: ");
    result.append(visibilite);
    result.append(')');
    return result.toString();
  }

} //CheminImpl
