/**
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.gAME.impl;

import fr.enseeiht.gAME.Connaissance;
import fr.enseeiht.gAME.Explorateur;
import fr.enseeiht.gAME.GAMEPackage;
import fr.enseeiht.gAME.Lieu;
import fr.enseeiht.gAME.ObjetAvecQuantite;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Explorateur</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.gAME.impl.ExplorateurImpl#getName <em>Name</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.impl.ExplorateurImpl#getTaille <em>Taille</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.impl.ExplorateurImpl#getObjets <em>Objets</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.impl.ExplorateurImpl#getConnaissances <em>Connaissances</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.impl.ExplorateurImpl#getLocalisation <em>Localisation</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExplorateurImpl extends MinimalEObjectImpl.Container implements Explorateur
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getTaille() <em>Taille</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTaille()
   * @generated
   * @ordered
   */
  protected static final int TAILLE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getTaille() <em>Taille</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTaille()
   * @generated
   * @ordered
   */
  protected int taille = TAILLE_EDEFAULT;

  /**
   * The cached value of the '{@link #getObjets() <em>Objets</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObjets()
   * @generated
   * @ordered
   */
  protected EList<ObjetAvecQuantite> objets;

  /**
   * The cached value of the '{@link #getConnaissances() <em>Connaissances</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConnaissances()
   * @generated
   * @ordered
   */
  protected EList<Connaissance> connaissances;

  /**
   * The cached value of the '{@link #getLocalisation() <em>Localisation</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocalisation()
   * @generated
   * @ordered
   */
  protected Lieu localisation;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExplorateurImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GAMEPackage.Literals.EXPLORATEUR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GAMEPackage.EXPLORATEUR__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getTaille()
  {
    return taille;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTaille(int newTaille)
  {
    int oldTaille = taille;
    taille = newTaille;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GAMEPackage.EXPLORATEUR__TAILLE, oldTaille, taille));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ObjetAvecQuantite> getObjets()
  {
    if (objets == null)
    {
      objets = new EObjectResolvingEList<ObjetAvecQuantite>(ObjetAvecQuantite.class, this, GAMEPackage.EXPLORATEUR__OBJETS);
    }
    return objets;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Connaissance> getConnaissances()
  {
    if (connaissances == null)
    {
      connaissances = new EObjectResolvingEList<Connaissance>(Connaissance.class, this, GAMEPackage.EXPLORATEUR__CONNAISSANCES);
    }
    return connaissances;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Lieu getLocalisation()
  {
    if (localisation != null && localisation.eIsProxy())
    {
      InternalEObject oldLocalisation = (InternalEObject)localisation;
      localisation = (Lieu)eResolveProxy(oldLocalisation);
      if (localisation != oldLocalisation)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, GAMEPackage.EXPLORATEUR__LOCALISATION, oldLocalisation, localisation));
      }
    }
    return localisation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Lieu basicGetLocalisation()
  {
    return localisation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLocalisation(Lieu newLocalisation)
  {
    Lieu oldLocalisation = localisation;
    localisation = newLocalisation;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GAMEPackage.EXPLORATEUR__LOCALISATION, oldLocalisation, localisation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GAMEPackage.EXPLORATEUR__NAME:
        return getName();
      case GAMEPackage.EXPLORATEUR__TAILLE:
        return getTaille();
      case GAMEPackage.EXPLORATEUR__OBJETS:
        return getObjets();
      case GAMEPackage.EXPLORATEUR__CONNAISSANCES:
        return getConnaissances();
      case GAMEPackage.EXPLORATEUR__LOCALISATION:
        if (resolve) return getLocalisation();
        return basicGetLocalisation();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GAMEPackage.EXPLORATEUR__NAME:
        setName((String)newValue);
        return;
      case GAMEPackage.EXPLORATEUR__TAILLE:
        setTaille((Integer)newValue);
        return;
      case GAMEPackage.EXPLORATEUR__OBJETS:
        getObjets().clear();
        getObjets().addAll((Collection<? extends ObjetAvecQuantite>)newValue);
        return;
      case GAMEPackage.EXPLORATEUR__CONNAISSANCES:
        getConnaissances().clear();
        getConnaissances().addAll((Collection<? extends Connaissance>)newValue);
        return;
      case GAMEPackage.EXPLORATEUR__LOCALISATION:
        setLocalisation((Lieu)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GAMEPackage.EXPLORATEUR__NAME:
        setName(NAME_EDEFAULT);
        return;
      case GAMEPackage.EXPLORATEUR__TAILLE:
        setTaille(TAILLE_EDEFAULT);
        return;
      case GAMEPackage.EXPLORATEUR__OBJETS:
        getObjets().clear();
        return;
      case GAMEPackage.EXPLORATEUR__CONNAISSANCES:
        getConnaissances().clear();
        return;
      case GAMEPackage.EXPLORATEUR__LOCALISATION:
        setLocalisation((Lieu)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GAMEPackage.EXPLORATEUR__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case GAMEPackage.EXPLORATEUR__TAILLE:
        return taille != TAILLE_EDEFAULT;
      case GAMEPackage.EXPLORATEUR__OBJETS:
        return objets != null && !objets.isEmpty();
      case GAMEPackage.EXPLORATEUR__CONNAISSANCES:
        return connaissances != null && !connaissances.isEmpty();
      case GAMEPackage.EXPLORATEUR__LOCALISATION:
        return localisation != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", taille: ");
    result.append(taille);
    result.append(')');
    return result.toString();
  }

} //ExplorateurImpl
