/**
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.ide;

import fr.enseeiht.ide.AbstractGAMEIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GAMEIdeModule extends AbstractGAMEIdeModule {
}
