/**
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.ui;

import fr.enseeiht.ui.AbstractGAMEUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class GAMEUiModule extends AbstractGAMEUiModule {
  public GAMEUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
