/*
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.ui.tests;

import com.google.inject.Injector;
import fr.enseeiht.game.ui.internal.GameActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class GAMEUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GameActivator.getInstance().getInjector("fr.enseeiht.GAME");
	}

}
