/*
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGAMEScopeProvider extends DelegatingScopeProvider {
}
