/*
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GAMEAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/enseeiht/parser/antlr/internal/InternalGAME.tokens");
	}
}
