/**
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.gAME;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Chemin</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.gAME.Chemin#getName <em>Name</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.Chemin#getDescriptions <em>Descriptions</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.Chemin#getDepart <em>Depart</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.Chemin#getArrive <em>Arrive</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.Chemin#getVisibilite <em>Visibilite</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.Chemin#getConditionsVisibilite <em>Conditions Visibilite</em>}</li>
 * </ul>
 *
 * @see fr.enseeiht.gAME.GAMEPackage#getChemin()
 * @model
 * @generated
 */
public interface Chemin extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.enseeiht.gAME.GAMEPackage#getChemin_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.enseeiht.gAME.Chemin#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Descriptions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Descriptions</em>' containment reference.
   * @see #setDescriptions(Description)
   * @see fr.enseeiht.gAME.GAMEPackage#getChemin_Descriptions()
   * @model containment="true"
   * @generated
   */
  Description getDescriptions();

  /**
   * Sets the value of the '{@link fr.enseeiht.gAME.Chemin#getDescriptions <em>Descriptions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Descriptions</em>' containment reference.
   * @see #getDescriptions()
   * @generated
   */
  void setDescriptions(Description value);

  /**
   * Returns the value of the '<em><b>Depart</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Depart</em>' reference.
   * @see #setDepart(Lieu)
   * @see fr.enseeiht.gAME.GAMEPackage#getChemin_Depart()
   * @model
   * @generated
   */
  Lieu getDepart();

  /**
   * Sets the value of the '{@link fr.enseeiht.gAME.Chemin#getDepart <em>Depart</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Depart</em>' reference.
   * @see #getDepart()
   * @generated
   */
  void setDepart(Lieu value);

  /**
   * Returns the value of the '<em><b>Arrive</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arrive</em>' reference.
   * @see #setArrive(Lieu)
   * @see fr.enseeiht.gAME.GAMEPackage#getChemin_Arrive()
   * @model
   * @generated
   */
  Lieu getArrive();

  /**
   * Sets the value of the '{@link fr.enseeiht.gAME.Chemin#getArrive <em>Arrive</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arrive</em>' reference.
   * @see #getArrive()
   * @generated
   */
  void setArrive(Lieu value);

  /**
   * Returns the value of the '<em><b>Visibilite</b></em>' attribute.
   * The literals are from the enumeration {@link fr.enseeiht.gAME.Visibilite}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visibilite</em>' attribute.
   * @see fr.enseeiht.gAME.Visibilite
   * @see #setVisibilite(Visibilite)
   * @see fr.enseeiht.gAME.GAMEPackage#getChemin_Visibilite()
   * @model
   * @generated
   */
  Visibilite getVisibilite();

  /**
   * Sets the value of the '{@link fr.enseeiht.gAME.Chemin#getVisibilite <em>Visibilite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visibilite</em>' attribute.
   * @see fr.enseeiht.gAME.Visibilite
   * @see #getVisibilite()
   * @generated
   */
  void setVisibilite(Visibilite value);

  /**
   * Returns the value of the '<em><b>Conditions Visibilite</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions Visibilite</em>' containment reference.
   * @see #setConditionsVisibilite(Condition)
   * @see fr.enseeiht.gAME.GAMEPackage#getChemin_ConditionsVisibilite()
   * @model containment="true"
   * @generated
   */
  Condition getConditionsVisibilite();

  /**
   * Sets the value of the '{@link fr.enseeiht.gAME.Chemin#getConditionsVisibilite <em>Conditions Visibilite</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conditions Visibilite</em>' containment reference.
   * @see #getConditionsVisibilite()
   * @generated
   */
  void setConditionsVisibilite(Condition value);

} // Chemin
