/**
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.gAME;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.enseeiht.gAME.GAMEFactory
 * @model kind="package"
 * @generated
 */
public interface GAMEPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "gAME";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.enseeiht.fr/GAME";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "gAME";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GAMEPackage eINSTANCE = fr.enseeiht.gAME.impl.GAMEPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.enseeiht.gAME.impl.JeuImpl <em>Jeu</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.enseeiht.gAME.impl.JeuImpl
   * @see fr.enseeiht.gAME.impl.GAMEPackageImpl#getJeu()
   * @generated
   */
  int JEU = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JEU__NAME = 0;

  /**
   * The feature id for the '<em><b>Explorateur</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JEU__EXPLORATEUR = 1;

  /**
   * The feature id for the '<em><b>Lieux</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JEU__LIEUX = 2;

  /**
   * The feature id for the '<em><b>Objets</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JEU__OBJETS = 3;

  /**
   * The feature id for the '<em><b>Connaissances</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JEU__CONNAISSANCES = 4;

  /**
   * The feature id for the '<em><b>Personnes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JEU__PERSONNES = 5;

  /**
   * The feature id for the '<em><b>Chemins</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JEU__CHEMINS = 6;

  /**
   * The number of structural features of the '<em>Jeu</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JEU_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link fr.enseeiht.gAME.impl.CheminImpl <em>Chemin</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.enseeiht.gAME.impl.CheminImpl
   * @see fr.enseeiht.gAME.impl.GAMEPackageImpl#getChemin()
   * @generated
   */
  int CHEMIN = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__NAME = 0;

  /**
   * The feature id for the '<em><b>Descriptions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__DESCRIPTIONS = 1;

  /**
   * The feature id for the '<em><b>Depart</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__DEPART = 2;

  /**
   * The feature id for the '<em><b>Arrive</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__ARRIVE = 3;

  /**
   * The feature id for the '<em><b>Visibilite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__VISIBILITE = 4;

  /**
   * The feature id for the '<em><b>Conditions Visibilite</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__CONDITIONS_VISIBILITE = 5;

  /**
   * The number of structural features of the '<em>Chemin</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link fr.enseeiht.gAME.impl.PersonneImpl <em>Personne</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.enseeiht.gAME.impl.PersonneImpl
   * @see fr.enseeiht.gAME.impl.GAMEPackageImpl#getPersonne()
   * @generated
   */
  int PERSONNE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE__NAME = 0;

  /**
   * The feature id for the '<em><b>Descriptions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE__DESCRIPTIONS = 1;

  /**
   * The feature id for the '<em><b>Interaction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE__INTERACTION = 2;

  /**
   * The feature id for the '<em><b>Visibilite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE__VISIBILITE = 3;

  /**
   * The feature id for the '<em><b>Conditions Visibilite</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE__CONDITIONS_VISIBILITE = 4;

  /**
   * The number of structural features of the '<em>Personne</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link fr.enseeiht.gAME.impl.InteractionImpl <em>Interaction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.enseeiht.gAME.impl.InteractionImpl
   * @see fr.enseeiht.gAME.impl.GAMEPackageImpl#getInteraction()
   * @generated
   */
  int INTERACTION = 3;

  /**
   * The feature id for the '<em><b>Choix</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION__CHOIX = 0;

  /**
   * The number of structural features of the '<em>Interaction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.enseeiht.gAME.impl.ChoixImpl <em>Choix</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.enseeiht.gAME.impl.ChoixImpl
   * @see fr.enseeiht.gAME.impl.GAMEPackageImpl#getChoix()
   * @generated
   */
  int CHOIX = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX__NAME = 0;

  /**
   * The number of structural features of the '<em>Choix</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.enseeiht.gAME.impl.ObjetImpl <em>Objet</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.enseeiht.gAME.impl.ObjetImpl
   * @see fr.enseeiht.gAME.impl.GAMEPackageImpl#getObjet()
   * @generated
   */
  int OBJET = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__NAME = 0;

  /**
   * The feature id for the '<em><b>Descriptions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__DESCRIPTIONS = 1;

  /**
   * The feature id for the '<em><b>Taille</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__TAILLE = 2;

  /**
   * The number of structural features of the '<em>Objet</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.enseeiht.gAME.impl.DescriptionImpl <em>Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.enseeiht.gAME.impl.DescriptionImpl
   * @see fr.enseeiht.gAME.impl.GAMEPackageImpl#getDescription()
   * @generated
   */
  int DESCRIPTION = 6;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION__TEXT = 0;

  /**
   * The number of structural features of the '<em>Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.enseeiht.gAME.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.enseeiht.gAME.impl.ConditionImpl
   * @see fr.enseeiht.gAME.impl.GAMEPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__NAME = 0;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.enseeiht.gAME.impl.ConnaissanceImpl <em>Connaissance</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.enseeiht.gAME.impl.ConnaissanceImpl
   * @see fr.enseeiht.gAME.impl.GAMEPackageImpl#getConnaissance()
   * @generated
   */
  int CONNAISSANCE = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNAISSANCE__NAME = 0;

  /**
   * The number of structural features of the '<em>Connaissance</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNAISSANCE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.enseeiht.gAME.impl.ExplorateurImpl <em>Explorateur</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.enseeiht.gAME.impl.ExplorateurImpl
   * @see fr.enseeiht.gAME.impl.GAMEPackageImpl#getExplorateur()
   * @generated
   */
  int EXPLORATEUR = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLORATEUR__NAME = 0;

  /**
   * The feature id for the '<em><b>Taille</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLORATEUR__TAILLE = 1;

  /**
   * The feature id for the '<em><b>Objets</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLORATEUR__OBJETS = 2;

  /**
   * The feature id for the '<em><b>Connaissances</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLORATEUR__CONNAISSANCES = 3;

  /**
   * The feature id for the '<em><b>Localisation</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLORATEUR__LOCALISATION = 4;

  /**
   * The number of structural features of the '<em>Explorateur</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLORATEUR_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link fr.enseeiht.gAME.impl.LieuImpl <em>Lieu</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.enseeiht.gAME.impl.LieuImpl
   * @see fr.enseeiht.gAME.impl.GAMEPackageImpl#getLieu()
   * @generated
   */
  int LIEU = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__NAME = 0;

  /**
   * The feature id for the '<em><b>Descriptions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__DESCRIPTIONS = 1;

  /**
   * The feature id for the '<em><b>Objets</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__OBJETS = 2;

  /**
   * The feature id for the '<em><b>Connaissances</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__CONNAISSANCES = 3;

  /**
   * The feature id for the '<em><b>Personnes</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__PERSONNES = 4;

  /**
   * The number of structural features of the '<em>Lieu</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link fr.enseeiht.gAME.Visibilite <em>Visibilite</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.enseeiht.gAME.Visibilite
   * @see fr.enseeiht.gAME.impl.GAMEPackageImpl#getVisibilite()
   * @generated
   */
  int VISIBILITE = 11;


  /**
   * Returns the meta object for class '{@link fr.enseeiht.gAME.Jeu <em>Jeu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Jeu</em>'.
   * @see fr.enseeiht.gAME.Jeu
   * @generated
   */
  EClass getJeu();

  /**
   * Returns the meta object for the attribute '{@link fr.enseeiht.gAME.Jeu#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.enseeiht.gAME.Jeu#getName()
   * @see #getJeu()
   * @generated
   */
  EAttribute getJeu_Name();

  /**
   * Returns the meta object for the containment reference '{@link fr.enseeiht.gAME.Jeu#getExplorateur <em>Explorateur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Explorateur</em>'.
   * @see fr.enseeiht.gAME.Jeu#getExplorateur()
   * @see #getJeu()
   * @generated
   */
  EReference getJeu_Explorateur();

  /**
   * Returns the meta object for the containment reference list '{@link fr.enseeiht.gAME.Jeu#getLieux <em>Lieux</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lieux</em>'.
   * @see fr.enseeiht.gAME.Jeu#getLieux()
   * @see #getJeu()
   * @generated
   */
  EReference getJeu_Lieux();

  /**
   * Returns the meta object for the containment reference list '{@link fr.enseeiht.gAME.Jeu#getObjets <em>Objets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Objets</em>'.
   * @see fr.enseeiht.gAME.Jeu#getObjets()
   * @see #getJeu()
   * @generated
   */
  EReference getJeu_Objets();

  /**
   * Returns the meta object for the containment reference list '{@link fr.enseeiht.gAME.Jeu#getConnaissances <em>Connaissances</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Connaissances</em>'.
   * @see fr.enseeiht.gAME.Jeu#getConnaissances()
   * @see #getJeu()
   * @generated
   */
  EReference getJeu_Connaissances();

  /**
   * Returns the meta object for the containment reference list '{@link fr.enseeiht.gAME.Jeu#getPersonnes <em>Personnes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Personnes</em>'.
   * @see fr.enseeiht.gAME.Jeu#getPersonnes()
   * @see #getJeu()
   * @generated
   */
  EReference getJeu_Personnes();

  /**
   * Returns the meta object for the containment reference list '{@link fr.enseeiht.gAME.Jeu#getChemins <em>Chemins</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Chemins</em>'.
   * @see fr.enseeiht.gAME.Jeu#getChemins()
   * @see #getJeu()
   * @generated
   */
  EReference getJeu_Chemins();

  /**
   * Returns the meta object for class '{@link fr.enseeiht.gAME.Chemin <em>Chemin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Chemin</em>'.
   * @see fr.enseeiht.gAME.Chemin
   * @generated
   */
  EClass getChemin();

  /**
   * Returns the meta object for the attribute '{@link fr.enseeiht.gAME.Chemin#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.enseeiht.gAME.Chemin#getName()
   * @see #getChemin()
   * @generated
   */
  EAttribute getChemin_Name();

  /**
   * Returns the meta object for the containment reference '{@link fr.enseeiht.gAME.Chemin#getDescriptions <em>Descriptions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Descriptions</em>'.
   * @see fr.enseeiht.gAME.Chemin#getDescriptions()
   * @see #getChemin()
   * @generated
   */
  EReference getChemin_Descriptions();

  /**
   * Returns the meta object for the reference '{@link fr.enseeiht.gAME.Chemin#getDepart <em>Depart</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Depart</em>'.
   * @see fr.enseeiht.gAME.Chemin#getDepart()
   * @see #getChemin()
   * @generated
   */
  EReference getChemin_Depart();

  /**
   * Returns the meta object for the reference '{@link fr.enseeiht.gAME.Chemin#getArrive <em>Arrive</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Arrive</em>'.
   * @see fr.enseeiht.gAME.Chemin#getArrive()
   * @see #getChemin()
   * @generated
   */
  EReference getChemin_Arrive();

  /**
   * Returns the meta object for the attribute '{@link fr.enseeiht.gAME.Chemin#getVisibilite <em>Visibilite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visibilite</em>'.
   * @see fr.enseeiht.gAME.Chemin#getVisibilite()
   * @see #getChemin()
   * @generated
   */
  EAttribute getChemin_Visibilite();

  /**
   * Returns the meta object for the containment reference '{@link fr.enseeiht.gAME.Chemin#getConditionsVisibilite <em>Conditions Visibilite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Conditions Visibilite</em>'.
   * @see fr.enseeiht.gAME.Chemin#getConditionsVisibilite()
   * @see #getChemin()
   * @generated
   */
  EReference getChemin_ConditionsVisibilite();

  /**
   * Returns the meta object for class '{@link fr.enseeiht.gAME.Personne <em>Personne</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Personne</em>'.
   * @see fr.enseeiht.gAME.Personne
   * @generated
   */
  EClass getPersonne();

  /**
   * Returns the meta object for the attribute '{@link fr.enseeiht.gAME.Personne#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.enseeiht.gAME.Personne#getName()
   * @see #getPersonne()
   * @generated
   */
  EAttribute getPersonne_Name();

  /**
   * Returns the meta object for the containment reference '{@link fr.enseeiht.gAME.Personne#getDescriptions <em>Descriptions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Descriptions</em>'.
   * @see fr.enseeiht.gAME.Personne#getDescriptions()
   * @see #getPersonne()
   * @generated
   */
  EReference getPersonne_Descriptions();

  /**
   * Returns the meta object for the containment reference '{@link fr.enseeiht.gAME.Personne#getInteraction <em>Interaction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Interaction</em>'.
   * @see fr.enseeiht.gAME.Personne#getInteraction()
   * @see #getPersonne()
   * @generated
   */
  EReference getPersonne_Interaction();

  /**
   * Returns the meta object for the attribute '{@link fr.enseeiht.gAME.Personne#getVisibilite <em>Visibilite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visibilite</em>'.
   * @see fr.enseeiht.gAME.Personne#getVisibilite()
   * @see #getPersonne()
   * @generated
   */
  EAttribute getPersonne_Visibilite();

  /**
   * Returns the meta object for the containment reference '{@link fr.enseeiht.gAME.Personne#getConditionsVisibilite <em>Conditions Visibilite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Conditions Visibilite</em>'.
   * @see fr.enseeiht.gAME.Personne#getConditionsVisibilite()
   * @see #getPersonne()
   * @generated
   */
  EReference getPersonne_ConditionsVisibilite();

  /**
   * Returns the meta object for class '{@link fr.enseeiht.gAME.Interaction <em>Interaction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Interaction</em>'.
   * @see fr.enseeiht.gAME.Interaction
   * @generated
   */
  EClass getInteraction();

  /**
   * Returns the meta object for the containment reference list '{@link fr.enseeiht.gAME.Interaction#getChoix <em>Choix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Choix</em>'.
   * @see fr.enseeiht.gAME.Interaction#getChoix()
   * @see #getInteraction()
   * @generated
   */
  EReference getInteraction_Choix();

  /**
   * Returns the meta object for class '{@link fr.enseeiht.gAME.Choix <em>Choix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Choix</em>'.
   * @see fr.enseeiht.gAME.Choix
   * @generated
   */
  EClass getChoix();

  /**
   * Returns the meta object for the attribute '{@link fr.enseeiht.gAME.Choix#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.enseeiht.gAME.Choix#getName()
   * @see #getChoix()
   * @generated
   */
  EAttribute getChoix_Name();

  /**
   * Returns the meta object for class '{@link fr.enseeiht.gAME.Objet <em>Objet</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Objet</em>'.
   * @see fr.enseeiht.gAME.Objet
   * @generated
   */
  EClass getObjet();

  /**
   * Returns the meta object for the attribute '{@link fr.enseeiht.gAME.Objet#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.enseeiht.gAME.Objet#getName()
   * @see #getObjet()
   * @generated
   */
  EAttribute getObjet_Name();

  /**
   * Returns the meta object for the containment reference list '{@link fr.enseeiht.gAME.Objet#getDescriptions <em>Descriptions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Descriptions</em>'.
   * @see fr.enseeiht.gAME.Objet#getDescriptions()
   * @see #getObjet()
   * @generated
   */
  EReference getObjet_Descriptions();

  /**
   * Returns the meta object for the attribute '{@link fr.enseeiht.gAME.Objet#getTaille <em>Taille</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Taille</em>'.
   * @see fr.enseeiht.gAME.Objet#getTaille()
   * @see #getObjet()
   * @generated
   */
  EAttribute getObjet_Taille();

  /**
   * Returns the meta object for class '{@link fr.enseeiht.gAME.Description <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Description</em>'.
   * @see fr.enseeiht.gAME.Description
   * @generated
   */
  EClass getDescription();

  /**
   * Returns the meta object for the attribute '{@link fr.enseeiht.gAME.Description#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see fr.enseeiht.gAME.Description#getText()
   * @see #getDescription()
   * @generated
   */
  EAttribute getDescription_Text();

  /**
   * Returns the meta object for class '{@link fr.enseeiht.gAME.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see fr.enseeiht.gAME.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the attribute '{@link fr.enseeiht.gAME.Condition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.enseeiht.gAME.Condition#getName()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Name();

  /**
   * Returns the meta object for class '{@link fr.enseeiht.gAME.Connaissance <em>Connaissance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Connaissance</em>'.
   * @see fr.enseeiht.gAME.Connaissance
   * @generated
   */
  EClass getConnaissance();

  /**
   * Returns the meta object for the attribute '{@link fr.enseeiht.gAME.Connaissance#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.enseeiht.gAME.Connaissance#getName()
   * @see #getConnaissance()
   * @generated
   */
  EAttribute getConnaissance_Name();

  /**
   * Returns the meta object for class '{@link fr.enseeiht.gAME.Explorateur <em>Explorateur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Explorateur</em>'.
   * @see fr.enseeiht.gAME.Explorateur
   * @generated
   */
  EClass getExplorateur();

  /**
   * Returns the meta object for the attribute '{@link fr.enseeiht.gAME.Explorateur#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.enseeiht.gAME.Explorateur#getName()
   * @see #getExplorateur()
   * @generated
   */
  EAttribute getExplorateur_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.enseeiht.gAME.Explorateur#getTaille <em>Taille</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Taille</em>'.
   * @see fr.enseeiht.gAME.Explorateur#getTaille()
   * @see #getExplorateur()
   * @generated
   */
  EAttribute getExplorateur_Taille();

  /**
   * Returns the meta object for the reference list '{@link fr.enseeiht.gAME.Explorateur#getObjets <em>Objets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Objets</em>'.
   * @see fr.enseeiht.gAME.Explorateur#getObjets()
   * @see #getExplorateur()
   * @generated
   */
  EReference getExplorateur_Objets();

  /**
   * Returns the meta object for the reference list '{@link fr.enseeiht.gAME.Explorateur#getConnaissances <em>Connaissances</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Connaissances</em>'.
   * @see fr.enseeiht.gAME.Explorateur#getConnaissances()
   * @see #getExplorateur()
   * @generated
   */
  EReference getExplorateur_Connaissances();

  /**
   * Returns the meta object for the reference '{@link fr.enseeiht.gAME.Explorateur#getLocalisation <em>Localisation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Localisation</em>'.
   * @see fr.enseeiht.gAME.Explorateur#getLocalisation()
   * @see #getExplorateur()
   * @generated
   */
  EReference getExplorateur_Localisation();

  /**
   * Returns the meta object for class '{@link fr.enseeiht.gAME.Lieu <em>Lieu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lieu</em>'.
   * @see fr.enseeiht.gAME.Lieu
   * @generated
   */
  EClass getLieu();

  /**
   * Returns the meta object for the attribute '{@link fr.enseeiht.gAME.Lieu#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.enseeiht.gAME.Lieu#getName()
   * @see #getLieu()
   * @generated
   */
  EAttribute getLieu_Name();

  /**
   * Returns the meta object for the containment reference list '{@link fr.enseeiht.gAME.Lieu#getDescriptions <em>Descriptions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Descriptions</em>'.
   * @see fr.enseeiht.gAME.Lieu#getDescriptions()
   * @see #getLieu()
   * @generated
   */
  EReference getLieu_Descriptions();

  /**
   * Returns the meta object for the reference list '{@link fr.enseeiht.gAME.Lieu#getObjets <em>Objets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Objets</em>'.
   * @see fr.enseeiht.gAME.Lieu#getObjets()
   * @see #getLieu()
   * @generated
   */
  EReference getLieu_Objets();

  /**
   * Returns the meta object for the reference list '{@link fr.enseeiht.gAME.Lieu#getConnaissances <em>Connaissances</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Connaissances</em>'.
   * @see fr.enseeiht.gAME.Lieu#getConnaissances()
   * @see #getLieu()
   * @generated
   */
  EReference getLieu_Connaissances();

  /**
   * Returns the meta object for the reference list '{@link fr.enseeiht.gAME.Lieu#getPersonnes <em>Personnes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Personnes</em>'.
   * @see fr.enseeiht.gAME.Lieu#getPersonnes()
   * @see #getLieu()
   * @generated
   */
  EReference getLieu_Personnes();

  /**
   * Returns the meta object for enum '{@link fr.enseeiht.gAME.Visibilite <em>Visibilite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Visibilite</em>'.
   * @see fr.enseeiht.gAME.Visibilite
   * @generated
   */
  EEnum getVisibilite();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GAMEFactory getGAMEFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.enseeiht.gAME.impl.JeuImpl <em>Jeu</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.enseeiht.gAME.impl.JeuImpl
     * @see fr.enseeiht.gAME.impl.GAMEPackageImpl#getJeu()
     * @generated
     */
    EClass JEU = eINSTANCE.getJeu();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JEU__NAME = eINSTANCE.getJeu_Name();

    /**
     * The meta object literal for the '<em><b>Explorateur</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JEU__EXPLORATEUR = eINSTANCE.getJeu_Explorateur();

    /**
     * The meta object literal for the '<em><b>Lieux</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JEU__LIEUX = eINSTANCE.getJeu_Lieux();

    /**
     * The meta object literal for the '<em><b>Objets</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JEU__OBJETS = eINSTANCE.getJeu_Objets();

    /**
     * The meta object literal for the '<em><b>Connaissances</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JEU__CONNAISSANCES = eINSTANCE.getJeu_Connaissances();

    /**
     * The meta object literal for the '<em><b>Personnes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JEU__PERSONNES = eINSTANCE.getJeu_Personnes();

    /**
     * The meta object literal for the '<em><b>Chemins</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JEU__CHEMINS = eINSTANCE.getJeu_Chemins();

    /**
     * The meta object literal for the '{@link fr.enseeiht.gAME.impl.CheminImpl <em>Chemin</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.enseeiht.gAME.impl.CheminImpl
     * @see fr.enseeiht.gAME.impl.GAMEPackageImpl#getChemin()
     * @generated
     */
    EClass CHEMIN = eINSTANCE.getChemin();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHEMIN__NAME = eINSTANCE.getChemin_Name();

    /**
     * The meta object literal for the '<em><b>Descriptions</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHEMIN__DESCRIPTIONS = eINSTANCE.getChemin_Descriptions();

    /**
     * The meta object literal for the '<em><b>Depart</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHEMIN__DEPART = eINSTANCE.getChemin_Depart();

    /**
     * The meta object literal for the '<em><b>Arrive</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHEMIN__ARRIVE = eINSTANCE.getChemin_Arrive();

    /**
     * The meta object literal for the '<em><b>Visibilite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHEMIN__VISIBILITE = eINSTANCE.getChemin_Visibilite();

    /**
     * The meta object literal for the '<em><b>Conditions Visibilite</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHEMIN__CONDITIONS_VISIBILITE = eINSTANCE.getChemin_ConditionsVisibilite();

    /**
     * The meta object literal for the '{@link fr.enseeiht.gAME.impl.PersonneImpl <em>Personne</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.enseeiht.gAME.impl.PersonneImpl
     * @see fr.enseeiht.gAME.impl.GAMEPackageImpl#getPersonne()
     * @generated
     */
    EClass PERSONNE = eINSTANCE.getPersonne();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSONNE__NAME = eINSTANCE.getPersonne_Name();

    /**
     * The meta object literal for the '<em><b>Descriptions</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSONNE__DESCRIPTIONS = eINSTANCE.getPersonne_Descriptions();

    /**
     * The meta object literal for the '<em><b>Interaction</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSONNE__INTERACTION = eINSTANCE.getPersonne_Interaction();

    /**
     * The meta object literal for the '<em><b>Visibilite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSONNE__VISIBILITE = eINSTANCE.getPersonne_Visibilite();

    /**
     * The meta object literal for the '<em><b>Conditions Visibilite</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSONNE__CONDITIONS_VISIBILITE = eINSTANCE.getPersonne_ConditionsVisibilite();

    /**
     * The meta object literal for the '{@link fr.enseeiht.gAME.impl.InteractionImpl <em>Interaction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.enseeiht.gAME.impl.InteractionImpl
     * @see fr.enseeiht.gAME.impl.GAMEPackageImpl#getInteraction()
     * @generated
     */
    EClass INTERACTION = eINSTANCE.getInteraction();

    /**
     * The meta object literal for the '<em><b>Choix</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERACTION__CHOIX = eINSTANCE.getInteraction_Choix();

    /**
     * The meta object literal for the '{@link fr.enseeiht.gAME.impl.ChoixImpl <em>Choix</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.enseeiht.gAME.impl.ChoixImpl
     * @see fr.enseeiht.gAME.impl.GAMEPackageImpl#getChoix()
     * @generated
     */
    EClass CHOIX = eINSTANCE.getChoix();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHOIX__NAME = eINSTANCE.getChoix_Name();

    /**
     * The meta object literal for the '{@link fr.enseeiht.gAME.impl.ObjetImpl <em>Objet</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.enseeiht.gAME.impl.ObjetImpl
     * @see fr.enseeiht.gAME.impl.GAMEPackageImpl#getObjet()
     * @generated
     */
    EClass OBJET = eINSTANCE.getObjet();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJET__NAME = eINSTANCE.getObjet_Name();

    /**
     * The meta object literal for the '<em><b>Descriptions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJET__DESCRIPTIONS = eINSTANCE.getObjet_Descriptions();

    /**
     * The meta object literal for the '<em><b>Taille</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJET__TAILLE = eINSTANCE.getObjet_Taille();

    /**
     * The meta object literal for the '{@link fr.enseeiht.gAME.impl.DescriptionImpl <em>Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.enseeiht.gAME.impl.DescriptionImpl
     * @see fr.enseeiht.gAME.impl.GAMEPackageImpl#getDescription()
     * @generated
     */
    EClass DESCRIPTION = eINSTANCE.getDescription();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DESCRIPTION__TEXT = eINSTANCE.getDescription_Text();

    /**
     * The meta object literal for the '{@link fr.enseeiht.gAME.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.enseeiht.gAME.impl.ConditionImpl
     * @see fr.enseeiht.gAME.impl.GAMEPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__NAME = eINSTANCE.getCondition_Name();

    /**
     * The meta object literal for the '{@link fr.enseeiht.gAME.impl.ConnaissanceImpl <em>Connaissance</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.enseeiht.gAME.impl.ConnaissanceImpl
     * @see fr.enseeiht.gAME.impl.GAMEPackageImpl#getConnaissance()
     * @generated
     */
    EClass CONNAISSANCE = eINSTANCE.getConnaissance();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNAISSANCE__NAME = eINSTANCE.getConnaissance_Name();

    /**
     * The meta object literal for the '{@link fr.enseeiht.gAME.impl.ExplorateurImpl <em>Explorateur</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.enseeiht.gAME.impl.ExplorateurImpl
     * @see fr.enseeiht.gAME.impl.GAMEPackageImpl#getExplorateur()
     * @generated
     */
    EClass EXPLORATEUR = eINSTANCE.getExplorateur();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPLORATEUR__NAME = eINSTANCE.getExplorateur_Name();

    /**
     * The meta object literal for the '<em><b>Taille</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPLORATEUR__TAILLE = eINSTANCE.getExplorateur_Taille();

    /**
     * The meta object literal for the '<em><b>Objets</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPLORATEUR__OBJETS = eINSTANCE.getExplorateur_Objets();

    /**
     * The meta object literal for the '<em><b>Connaissances</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPLORATEUR__CONNAISSANCES = eINSTANCE.getExplorateur_Connaissances();

    /**
     * The meta object literal for the '<em><b>Localisation</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPLORATEUR__LOCALISATION = eINSTANCE.getExplorateur_Localisation();

    /**
     * The meta object literal for the '{@link fr.enseeiht.gAME.impl.LieuImpl <em>Lieu</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.enseeiht.gAME.impl.LieuImpl
     * @see fr.enseeiht.gAME.impl.GAMEPackageImpl#getLieu()
     * @generated
     */
    EClass LIEU = eINSTANCE.getLieu();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIEU__NAME = eINSTANCE.getLieu_Name();

    /**
     * The meta object literal for the '<em><b>Descriptions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIEU__DESCRIPTIONS = eINSTANCE.getLieu_Descriptions();

    /**
     * The meta object literal for the '<em><b>Objets</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIEU__OBJETS = eINSTANCE.getLieu_Objets();

    /**
     * The meta object literal for the '<em><b>Connaissances</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIEU__CONNAISSANCES = eINSTANCE.getLieu_Connaissances();

    /**
     * The meta object literal for the '<em><b>Personnes</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIEU__PERSONNES = eINSTANCE.getLieu_Personnes();

    /**
     * The meta object literal for the '{@link fr.enseeiht.gAME.Visibilite <em>Visibilite</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.enseeiht.gAME.Visibilite
     * @see fr.enseeiht.gAME.impl.GAMEPackageImpl#getVisibilite()
     * @generated
     */
    EEnum VISIBILITE = eINSTANCE.getVisibilite();

  }

} //GAMEPackage
