/**
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.gAME;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Jeu</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.gAME.Jeu#getName <em>Name</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.Jeu#getExplorateur <em>Explorateur</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.Jeu#getPointDepart <em>Point Depart</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.Jeu#getPointFin <em>Point Fin</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.Jeu#getLieux <em>Lieux</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.Jeu#getObjets <em>Objets</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.Jeu#getObjetAvecQuantite <em>Objet Avec Quantite</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.Jeu#getConnaissances <em>Connaissances</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.Jeu#getPersonnes <em>Personnes</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.Jeu#getChemins <em>Chemins</em>}</li>
 * </ul>
 *
 * @see fr.enseeiht.gAME.GAMEPackage#getJeu()
 * @model
 * @generated
 */
public interface Jeu extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.enseeiht.gAME.GAMEPackage#getJeu_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.enseeiht.gAME.Jeu#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Explorateur</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Explorateur</em>' containment reference.
   * @see #setExplorateur(Explorateur)
   * @see fr.enseeiht.gAME.GAMEPackage#getJeu_Explorateur()
   * @model containment="true"
   * @generated
   */
  Explorateur getExplorateur();

  /**
   * Sets the value of the '{@link fr.enseeiht.gAME.Jeu#getExplorateur <em>Explorateur</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Explorateur</em>' containment reference.
   * @see #getExplorateur()
   * @generated
   */
  void setExplorateur(Explorateur value);

  /**
   * Returns the value of the '<em><b>Point Depart</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Point Depart</em>' reference.
   * @see #setPointDepart(Lieu)
   * @see fr.enseeiht.gAME.GAMEPackage#getJeu_PointDepart()
   * @model
   * @generated
   */
  Lieu getPointDepart();

  /**
   * Sets the value of the '{@link fr.enseeiht.gAME.Jeu#getPointDepart <em>Point Depart</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Point Depart</em>' reference.
   * @see #getPointDepart()
   * @generated
   */
  void setPointDepart(Lieu value);

  /**
   * Returns the value of the '<em><b>Point Fin</b></em>' reference list.
   * The list contents are of type {@link fr.enseeiht.gAME.Lieu}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Point Fin</em>' reference list.
   * @see fr.enseeiht.gAME.GAMEPackage#getJeu_PointFin()
   * @model
   * @generated
   */
  EList<Lieu> getPointFin();

  /**
   * Returns the value of the '<em><b>Lieux</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gAME.Lieu}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lieux</em>' containment reference list.
   * @see fr.enseeiht.gAME.GAMEPackage#getJeu_Lieux()
   * @model containment="true"
   * @generated
   */
  EList<Lieu> getLieux();

  /**
   * Returns the value of the '<em><b>Objets</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gAME.Objet}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objets</em>' containment reference list.
   * @see fr.enseeiht.gAME.GAMEPackage#getJeu_Objets()
   * @model containment="true"
   * @generated
   */
  EList<Objet> getObjets();

  /**
   * Returns the value of the '<em><b>Objet Avec Quantite</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gAME.ObjetAvecQuantite}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objet Avec Quantite</em>' containment reference list.
   * @see fr.enseeiht.gAME.GAMEPackage#getJeu_ObjetAvecQuantite()
   * @model containment="true"
   * @generated
   */
  EList<ObjetAvecQuantite> getObjetAvecQuantite();

  /**
   * Returns the value of the '<em><b>Connaissances</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gAME.Connaissance}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connaissances</em>' containment reference list.
   * @see fr.enseeiht.gAME.GAMEPackage#getJeu_Connaissances()
   * @model containment="true"
   * @generated
   */
  EList<Connaissance> getConnaissances();

  /**
   * Returns the value of the '<em><b>Personnes</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gAME.Personne}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Personnes</em>' containment reference list.
   * @see fr.enseeiht.gAME.GAMEPackage#getJeu_Personnes()
   * @model containment="true"
   * @generated
   */
  EList<Personne> getPersonnes();

  /**
   * Returns the value of the '<em><b>Chemins</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gAME.Chemin}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Chemins</em>' containment reference list.
   * @see fr.enseeiht.gAME.GAMEPackage#getJeu_Chemins()
   * @model containment="true"
   * @generated
   */
  EList<Chemin> getChemins();

} // Jeu
