/**
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.gAME;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lieu</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.gAME.Lieu#getName <em>Name</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.Lieu#getDescriptions <em>Descriptions</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.Lieu#getObjets <em>Objets</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.Lieu#getConnaissances <em>Connaissances</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.Lieu#getPersonnes <em>Personnes</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.Lieu#getCheminspossible <em>Cheminspossible</em>}</li>
 * </ul>
 *
 * @see fr.enseeiht.gAME.GAMEPackage#getLieu()
 * @model
 * @generated
 */
public interface Lieu extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.enseeiht.gAME.GAMEPackage#getLieu_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.enseeiht.gAME.Lieu#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Descriptions</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gAME.Description}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Descriptions</em>' containment reference list.
   * @see fr.enseeiht.gAME.GAMEPackage#getLieu_Descriptions()
   * @model containment="true"
   * @generated
   */
  EList<Description> getDescriptions();

  /**
   * Returns the value of the '<em><b>Objets</b></em>' reference list.
   * The list contents are of type {@link fr.enseeiht.gAME.Objet}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objets</em>' reference list.
   * @see fr.enseeiht.gAME.GAMEPackage#getLieu_Objets()
   * @model
   * @generated
   */
  EList<Objet> getObjets();

  /**
   * Returns the value of the '<em><b>Connaissances</b></em>' reference list.
   * The list contents are of type {@link fr.enseeiht.gAME.Connaissance}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connaissances</em>' reference list.
   * @see fr.enseeiht.gAME.GAMEPackage#getLieu_Connaissances()
   * @model
   * @generated
   */
  EList<Connaissance> getConnaissances();

  /**
   * Returns the value of the '<em><b>Personnes</b></em>' reference list.
   * The list contents are of type {@link fr.enseeiht.gAME.Personne}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Personnes</em>' reference list.
   * @see fr.enseeiht.gAME.GAMEPackage#getLieu_Personnes()
   * @model
   * @generated
   */
  EList<Personne> getPersonnes();

  /**
   * Returns the value of the '<em><b>Cheminspossible</b></em>' reference list.
   * The list contents are of type {@link fr.enseeiht.gAME.Chemin}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cheminspossible</em>' reference list.
   * @see fr.enseeiht.gAME.GAMEPackage#getLieu_Cheminspossible()
   * @model
   * @generated
   */
  EList<Chemin> getCheminspossible();

} // Lieu
