/**
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.gAME;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Objet Avec Quantite</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.gAME.ObjetAvecQuantite#getName <em>Name</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.ObjetAvecQuantite#getObjet <em>Objet</em>}</li>
 *   <li>{@link fr.enseeiht.gAME.ObjetAvecQuantite#getQuantite <em>Quantite</em>}</li>
 * </ul>
 *
 * @see fr.enseeiht.gAME.GAMEPackage#getObjetAvecQuantite()
 * @model
 * @generated
 */
public interface ObjetAvecQuantite extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.enseeiht.gAME.GAMEPackage#getObjetAvecQuantite_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.enseeiht.gAME.ObjetAvecQuantite#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Objet</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objet</em>' reference.
   * @see #setObjet(Objet)
   * @see fr.enseeiht.gAME.GAMEPackage#getObjetAvecQuantite_Objet()
   * @model
   * @generated
   */
  Objet getObjet();

  /**
   * Sets the value of the '{@link fr.enseeiht.gAME.ObjetAvecQuantite#getObjet <em>Objet</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Objet</em>' reference.
   * @see #getObjet()
   * @generated
   */
  void setObjet(Objet value);

  /**
   * Returns the value of the '<em><b>Quantite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quantite</em>' attribute.
   * @see #setQuantite(int)
   * @see fr.enseeiht.gAME.GAMEPackage#getObjetAvecQuantite_Quantite()
   * @model
   * @generated
   */
  int getQuantite();

  /**
   * Sets the value of the '{@link fr.enseeiht.gAME.ObjetAvecQuantite#getQuantite <em>Quantite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quantite</em>' attribute.
   * @see #getQuantite()
   * @generated
   */
  void setQuantite(int value);

} // ObjetAvecQuantite
